### ISSUE TITLE
Developers: feel free to edit README to link to your names

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#10]
As I have done for myself, feel free to link your name to a personal webpage.

**Comment by DanielSank** [comment]
>  feel free to link your name to a personal webpage.

This issue should probably be to put that in the README.

**Comment by babbush** [comment]
Nah, we don't need more clutter in the README. I might just go in myself and link everybody who hasn't added a link to their GitHub page.

**Comment by DanielSank** [comment]
Ok consider making a `contributing.md` and linking that from the README. An added benefit is that when someone files a pull request, github automatically shows them a link to `contributing.md`!

**Comment by babbush** [comment]
This is a good idea.
