### ISSUE TITLE
v0.2 release notes

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#101]
Whenever we cut a new release we need to write a list of the new features. I also forget what all the new features are by that time. We should keep a running list of new features in this "issue". Whenever you fix a bug or add a feature, just mention it here and when we cut the release we'll include what your write in the release notes. I'll start with a couple of points.

**Comment by babbush** [comment]
* Generalized the InteractionTensor class to handle arbitrary marginals. Now called PolynomialTensor.
* Added a data structure for manipulating Majoranas called QuadraticHamiltonian

**Comment by kevinsung** [comment]
Ryan, I edited your comment because QuadraticHamiltonian uses Majoranas only internally, in contrast with my original plans that I discussed with you.

**Comment by kevinsung** [comment]
- Fixed a bug in `jordan_wigner_sparse` where Pauli-Z strings of the Jordan-Wigner Transform were placed on higher indices rather than lower.
- Added code to obtain arbitrary eigenstates of quadratic Hamiltonians (a.k.a. fermionic Gaussian states) and circuits to prepare them.
