### ISSUE TITLE
papers that use OpenFermion

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#119]
I think it would be nice to keep a list of publications that use OpenFermion in some way. Perhaps when people publish a new paper they can mention it here and give a small description. Since I have put out several papers using OpenFermion I will start us off. Maybe at some later point when (and if) we make an OpenFermion website other than GitHub, we can publish a nicer list of these papers.

**Comment by babbush** [comment]
_Low Depth Quantum Simulation of Electronic Structure_. Ryan Babbush, Nathan Wiebe, Jarrod McClean, James McClain, Hartmut Neven and Garnet Chan. [arXiv:1706.00023](https://arxiv.org/abs/1706.00023). 2017.

This paper discusses the use of special basis sets which change the structure of molecular Hamiltonians in order to obtain a simpler representations that is more efficient to simulate using quantum computers. We used OpenFermion to check a number of equations in the paper, especially derivations involving the fermionic Fourier transform. We also used OpenFermion to check bounds of operators and the coefficients of Hamiltonians after transforming with Jordan-Wigner.

**Comment by babbush** [comment]
_Improved Techniques for Preparing Eigenstates of Fermionic Hamiltonians_. Ryan Babbush, Dominic Berry, Mária Kieferová, Guang Hao Low, Yuval Sanders, Artur Scherer and Nathan Wiebe. [arXiv:1711.10460](https://arxiv.org/abs/1711.10460). 2017.

This paper discusses several techniques for using the phase estimation algorithm to prepare ground states of fermionic systems with reduced overhead. The second result of the paper explains that in circumstances when one has knowledge of an upper-bound on the ground state energy that is tighter than the first excited state, one can use the knowledge to make fewer repetitions of the phase estimation algorithm. OpenFermion is used for some numerics in this paper which investigate the usefulness of this technique for the water molecule. To produce these numerics we used OpenFermion and OpenFermion-Psi4 to generate molecular Hamiltonians, computed an induced L1 norm of those Hamiltonians, checked ground state overlaps and obtained ground state and excited state energies.

**Comment by kanavsetia** [comment]
_Bravyi-Kitaev_ Superfast simulation of fermions on a quantum computer._ Kanav Setia, James D. Whitfield. [arXiv:1712.00446v1](https://arxiv.org/abs/1712.00446). 2017

This paper details the Bravyi-Kitaev Superfast (BKSF) algorithm implemented in the OpenFermion. Starting from the electronic Hamiltonian, the details for mapping all the fermionic operators to qubit operators using BKSF transform are presented. Hydrogen molecule is used as test case in the paper and the final qubit Hamiltonian using BKSF transform is presented. The results section compares Jordan-Wigner, Bravyi-Kitaev, and BKSF algorithms using Trotterization.

All the expressions used in the OpenFermion code for BKSF algorithm are described in the paper.
Test case of hydrogen molecule in the paper was used to develop test routines for the code. [OpenFermion-Psi4](https://github.com/quantumlib/OpenFermion-Psi4) was used to get the integrals for the hydrogen molecule.

**Comment by kevinsung** [comment]
_Quantum algorithms to simulate many-body physics of correlated fermions_. Zhang Jiang, Kevin J. Sung, Kostyantyn Kechedzhi, Vadim N. Smelyanskiy, and Sergio Boixo. [arXiv:1711.05395](https://arxiv.org/abs/1711.05395). 2017.

This paper gives quantum algorithms for preparing eigenstates of quadratic Hamiltonians and for performing the 2-d fermionic Fourier transform. The routines in OpenFermion for obtaining circuits to prepare Slater determinants and fermionic Gaussian states is based on the procedure described in this paper. The paper can be consulted to understand the circuit descriptions output by the code.

**Comment by idk3** [comment]
_Quantum simulation of electronic structure with linear depth and connectivity_. Ian D. Kivlichan, Jarrod McClean, Nathan Wiebe, Craig Gidney, Alán Aspuru-Guzik, Garnet Kin-Lic Chan, Ryan Babbush. [arXiv:1711.04789](https://arxiv.org/abs/1711.04789). 2017.

In this paper, we show that by using an arrangement of gates that we term the fermionic swap network, we can simulate a Trotter step of the electronic structure Hamiltonian in exactly N depth and with N^2/2 two-qubit entangling gates, and prepare arbitrary Slater determinants in at most N/2 depth, using only a minimal, linearly connected architecture. We used OpenFermion to verify numerically the Trotter step we developed. Our code is included in [OpenFermion-ProjectQ](https://github.com/quantumlib/OpenFermion-ProjectQ).

**Comment by jdaaph** [comment]
Efficient Implementation of Baker-Campbell-Hausdorff Formula 
Cupjin Huang  https://arxiv.org/abs/1712.01348.  2017

This short paper presents an efficient implementation of Baker-Campbell-Hausdorff formula for calculating the logarithm of product of two possibly non-commutative Lie group elements using only Lie algebra terms.

**Comment by ncrubin** [comment]
_Application of fermionic marginal constraints to hybrid quantum algorithms_
Nicholas C. Rubin, Ryan Babbush, Jarrod McClean. [arXiv:1801.03524](https://arxiv.org/abs/1801.03524). 2018.

This paper explores how geometric constraints on marginals of a fermionic density matrices can be used to augment various aspects of hybrid quantum algorithms. Linear constraints are used to reduce the number of measurements required for expectation value estimation and positivity constraints are used to design projection methods to certify marginals measured from a quantum devices.  Two important proofs are also provided: 1) an optimal measurement complexity for measuring expectation values of sums of non-commuting Pauli operators and 2) concentration of measure of the 1- and 2-marginal for random states.  OpenFermion and the OpenFermion-Psi4 plugins are used to create molecular data (hydrogen chains) to validate the proposed variance minimization and projection techniques.

**Comment by babbush** [comment]
At this point a lot of papers are using OpenFermion. I'm not sure if we still need this open.
