### ISSUE TITLE
Travis CI not running

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#128]
Unfortunately Travis is not automatically running on open pull requests anymore. We are not aware of any straightforward way to force Travis to run. Until this problem is fixed, we cannot merge any new PRs. Thus, this is a very high priority issue.

**Comment by dabacon** [comment]
I don't think that this leads to a solution, but note that you can trigger a travis build by going to travis-ci.org and then going to OpenFermion project and then triggering a manual build (see the "..." in upper right corner).

**Comment by babbush** [comment]
Unfortunately I only see an option to trigger a build of the master branch. But what I really want to do is trigger a build of the feature branch of an OpenFermion fork, from where the pull request is coming.

**Comment by babbush** [comment]
Mysteriously, the problem seems to be specific to PRs from @kevinsung

**Comment by babbush** [comment]
We have determined that the error is with Travis, not with OpenFermion. It pertains only to Kevin's account. We will get to the bottom of this but since it is not an  OpenFermion issue I will close.
