### ISSUE TITLE
OpenBoson?

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#151]
There are many reasons why one might want to study the physics of bosonic systems. Such is not the focus of OpenFermion but some limited functionalities for simulating bosons, or systems of interacting bosons and fermions, should be possible to incorporate. For instance, one might want to simulate models of molecules interacting with light which involve electrons and photons. There are also many reasons why one might wish to study systems with electron-phonon coupling, etc. Coupling fermionic systems to a harmonic bath is also common in the context of open quantum systems. If this is a direction which interests anyone, we should discuss implementation ideas here.

One thought is to first make a BosonOperator class. This would be much less onerous if (https://github.com/quantumlib/OpenFermion/issues/43) is first closed, since then one can create the BosonOperator through inheritance. If one restricts the number of bosons which may occupy a single mode then it is also straightforward to provide transforms which map the bosonic operators to QubitOperators. In order to study models of fermion-boson coupling one would need a class that can represent mixed operators. That too will require some thought and discussion. An excellent solution is not immediately obvious.

**Comment by pldallairedemers** [comment]
At Xanadu we are evaluating if we can make a significant contribution here that would also align with our business goals. I should have more details and questions in a few weeks.

**Comment by babbush** [comment]
This paper seems like it should be of interest for this issue: https://arxiv.org/abs/1802.07347

**Comment by babbush** [comment]
This was closed in #352
