### ISSUE TITLE
OpenFermion schwag

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#167]
Now that we have a prototype logo, it is time to start thinking about schwag. While we're not committing to anything at this point, I think it would be nice to have some sort of schwag made in time for APS March Meeting. We do have some sort of a budget for this.

What kind of schwag would people like to see? Shirts? Fleeces? Hoodies? It would be great if people could make design suggestions (e.g. OpenFermion logo in black / orange on the front right breast of a grey t-shirt and "from openfermion import *" on the back). It would be even more awesome if people could suggest very make / models and give a link.

Let's try to limit suggestions to items under $150, keeping in mind that the cheaper the item, the more likely we are to be able to pull it off. Anyone is welcome to comment on this thread.

@jarrodmcc 
@ncrubin 
@karlunho

**Comment by babbush** [comment]
Okay so perhaps let's just start with the assumption there are going to be shirts for APS March meeting with the OpenFermion logo on the front breast. Should we have openfermion.org/ written on the back? Perhaps with some slightly geeky slogan under it like:
"where anti-symmetry is beautiful"
"where electrons get quantum computed"
"quantum computing fermions since 2017"
etc.

Hopefully others have some better ideas?

**Comment by conta877** [comment]
mugs?

**Comment by babbush** [comment]
My main worry about mugs is just that I am much less inclined to want to haul mugs to a conference or something as opposed to a less breakable item like shirts. @jarrodmcc has convinced me that we don't necessarily need any words on the back. I feel like openfermion.org written somewhere (maybe in smallish letters on sleeve) would be good though.

**Comment by ncrubin** [comment]
@babbush mugs are hard to pack back from conferences. I think t-shirts are a great piece of swag for a large group.  I guess the purpose of "schwag"  is to get the product name out there...so if t-shirts are the cheapest and easiest to port around then I'd say go for it.  Stickers (to put on laptops or water bottles) are also a good way to go. 

On a less feasible note: It would be really awesome to have patagonia pull overs.  The quarter zips are $100 (requires a 10 item minimum purchase).  There are also cheaper options for fleeces (port-authority, northface, etc) that are around $50-80.  Obviously, we couldn't order TONS of these given a reasonable budget.

As for mugs/thermos/water bottle, there are plenty of options.  I think general corporate swag standard is something along the lines of Zojirushi, contigo, or s'well.

**Comment by babbush** [comment]
What about putting something like

quantum software for chemistry
openfermion.org

on the back? I am also thinking it could be fun to have a shirt in a different color that says "developer" on the sleeve. These are obviously the "cool" shirts and are perhaps made in some higher quality fabric. Anyone who contributes code and can find me at a conference would be entitled to those. The other ones would be more for promotion. What do people think about this?

I am happy to look into stickers, that is easy. I will look into fleeces but the first order of business is likely to be t-shirts and we can perhaps come back to fleeces after that.

**Comment by babbush** [comment]
Y'all were mostly not helpful with this. Some schwag has been ordered. A rough mockup is below.  The color is more of a textured black than gray. I'll bring some to APS.
![image](https://user-images.githubusercontent.com/14242687/35416521-3390379a-01de-11e8-9aeb-43ae3209fca3.png)
