### ISSUE TITLE
h5py warning

### ISSUE THREAD

**Issue by gaming-hacker** [quantumlib/OpenFermion#175]
hello,
OSX 10.12.6, clang-6.0, python2.7,numpy 1.14.0, scipy 1.0.0

installed openfermion from github repo as well as the plugins.

running the basic example
```
from openfermion.ops import FermionOperator, hermitian_conjugated
from openfermion.transforms import jordan_wigner, bravyi_kitaev
from openfermion.utils import eigenspectrum

# Initialize an operator.
fermion_operator = FermionOperator('2^ 0', 3.17)
fermion_operator += hermitian_conjugated(fermion_operator)
print(fermion_operator)
```

the following warning happens

.../h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

can someone confirm this solution is correct?
3.17 [2^ 0] +
3.17 [0^ 2]

**Comment by kevinsung** [comment]
The output you got is correct.

This is the same warning that I mentioned getting with Python2.7 in #173 . My details are
> Arch Linux with kernel version 4.14.11
Python 2.7.14
Jupyter notebook server version 5.0.0
numpy 1.14.0
scipy 1.0.0
h5py 2.7.1

I also get the warning when simply running `import openfermion`.

**Comment by babbush** [comment]
This seems to have come up very recently. It is just a warning, not a bug, and the code output still looks correct. This is likely due to something that changed recently in one of our dependancies. I'll take a look briefly tonight but may need to return to this tomorrow or Saturday - it doesn't seem critical (albeit ugly). Kudos to anyone else who tracks it down.

**Comment by kevinsung** [comment]
I just found out that I get the same warning from simply executing "import h5py". So I think this has nothing to do with OpenFermion.

**Comment by kevinsung** [comment]
From looking at https://github.com/h5py/h5py/issues/961, it appears that the h5py developers are aware of this issue and are currently working on a fix at https://github.com/h5py/h5py/pull/926.

**Comment by babbush** [comment]
Hmm, thanks Kevin. Unfortunately they haven't updated that PR in ten days. The funny thing though is that I cannot reproduce this error on my mac. @kevinsung @gaming-hacker What version of h5py are you running?

**Comment by kevinsung** [comment]
I'm using h5py 2.7.1

**Comment by babbush** [comment]
I see. I am using Anaconda python and their latest distribution only uses h5py 2.7.0 which seems to not have this problem. I guess we should just wait until h5py people get this fixed.

**Comment by gaming-hacker** [comment]
i'm using h5py (2.7.1)

**Comment by babbush** [comment]
Thanks! I think it might be helpful to leave the issue open just so people can see this easily if they encounter the warning. I have marked it as "not our fault". We can close whenever h5py fixes this.

**Comment by gaming-hacker** [comment]
i forked it and pulled in a few PRs and now without the warning

gaming-hacker/h5py

```
=>pycheck h5py
Summary of the h5py configuration
---------------------------------
h5py    2.7.1.post0
HDF5    1.10.1
Python  2.7.14 (default, Sep 22 2017, 00:06:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.14.0
```

**Comment by babbush** [comment]
Hmm, so the problem disappeared for you? Does this mean the h5py people fixed the issue?

**Comment by kevinsung** [comment]
I'm still getting the warning. I'm still on version 2.7.1 though and can't seem to get 2.7.1.post0.

**Comment by gaming-hacker** [comment]
h5py haven't merged the PRs to fix this issue into their master branch.  i forked my own repo, applied the correct PRs and now it works.

**Comment by kevinsung** [comment]
Cool. It looks like we just need to wait for them to release the next version, then we can close this issue.

**Comment by babbush** [comment]
Are people still seeing this bug?

**Comment by kevinsung** [comment]
I'm still getting the warning. The latest version of h5py on pip is still 2.7.1.

**Comment by babbush** [comment]
Still?

**Comment by kevinsung** [comment]
Yeah. This will be an issue at least until the next h5py version (after 2.7.1) is released on pip (https://pypi.python.org/pypi/h5py). Again, this has nothing to do with OpenFermion because I get the warning when I execute just `import h5py`.

**Comment by babbush** [comment]
A hacky way to suppress this from the issue on the h5py repo (where I recently complained):
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import h5py
warnings.resetwarnings()

Maybe it's better than always seeing this message? @kevinsung what do you think?

**Comment by kevinsung** [comment]
Thanks, that will be helpful for suppressing the warning in Jupyter notebook demos. I'm not sure that should actually go into our codebase though.

There is a new release candidate at https://pypi.python.org/pypi/h5py so hopefully this issue will be resolved soon!

**Comment by babbush** [comment]
People still getting this? I like to check every week or so, lol

**Comment by kevinsung** [comment]
Yup

**Comment by chenDeChao0808** [comment]
still
solutions?

**Comment by kevinsung** [comment]
The only real solution is to fix `h5py`, and by that I mean wait for the next production release to come out on https://pypi.python.org/pypi/h5py. @babbush gave a way to suppress the warning above:
```
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import h5py
warnings.resetwarnings()
```
For instance, you can put that in your IPython configuration file and then the warning will not show up in Jupyter.

**Comment by gaming-hacker** [comment]
i don't think you want to hack to disable the warnings, you're applying a bandaid that might break future builds or cause weird errors.  i'd suggest let h5py fix their issue.

**Comment by Manjunathsai7** [comment]
pip3 uninstall h5py 
pip3 install h5py==2.8.0rc1
this can fix problems . hope it will help you.

**Comment by aragilar** [comment]
@kevinsung The 2.8 release is now on PyPI, so you should be able to close this now.

**Comment by kevinsung** [comment]
Great!

**Comment by babbush** [comment]
I'm reopening because I still incur the error message on a fresh install of OpenFermion. I think we may need to bump the version requirement in requirements.txt for h5py.
