### ISSUE TITLE
Module for special operators

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#205]
I propose that we rename `hamiltonians/_fermion_spin_operators.py` to `hamiltonians/_special_operators.py` and move `number_operator` and `majorana_operator` to this file from `ops/_fermion_operator.py`. What do people think? @ncrubin @babbush

**Comment by babbush** [comment]
Sounds okay to me.

**Comment by ncrubin** [comment]
👍

**Comment by babbush** [comment]
Closed by #206
