### ISSUE TITLE
get_n_alpha_electrons & get_n_beta_electrons gives wrong result

### ISSUE THREAD

**Issue by Konjkov** [quantumlib/OpenFermion#234]
Hello all
get_n_alpha_electrons() & get_n_beta_electrons() functions gives wrong results
https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/hamiltonians/_molecular_data.py#L734

Multiplicity is a property that describes an atom’s or molecule’s electronic structure. The total number of alpha and beta electrons in an atom/molecule are needed to calculate multiplicity.
Before calculating multiplicity you first calculate total spin (S).
S = (# of alpha electrons)(+1/2) + (# of beta electrons)(-1/2) 
Multiplicity = |2S| + 1 

So right answer should be:
alpha electrons = (# total electrons + (Multiplicity - 1)) / 2
beta electrons = (# total electrons - (Multiplicity - 1)) / 2

PS:
also output value should be an INTEGER type, to fit parse_psi4_ccsd_amplitudes() input parameters type in
https://github.com/quantumlib/OpenFermion-Psi4/blob/master/openfermionpsi4/_psi4_template#L230

PPS:
actually it gives for ground state of C atom (mult=3) 5.0 alpha and 1.0 beta electrons.

best Vladimir.

**Comment by babbush** [comment]
Thanks for pointing this out. The issue has been corrected.
