### ISSUE TITLE
get_ground_state(sparse_operator) sometimes fails with SIGSEGV

### ISSUE THREAD

**Issue by Konjkov** [quantumlib/OpenFermion#235]
Hello OpenFermion developers
I have the code like

```
#!/usr/bin/env python3

from openfermion.hamiltonians import MolecularData
from openfermion.transforms import get_fermion_operator, get_sparse_operator, jordan_wigner
from openfermion.utils import get_ground_state
import numpy
import scipy
from scipy.sparse.linalg import eigsh
from scipy.linalg import eigh

# Load saved file for H.
geometry = [('Be', (0., 0., 0.))]
basis = 'cc-pVDZ'
multiplicity = 1

# Set Hamiltonian parameters.
active_space_start = 0
active_space_stop = 6

# Generate and populate instance of MolecularData.
molecule = MolecularData(geometry, basis, multiplicity, description="Be")
molecule.load()

# Get the Hamiltonian in an active space.
molecular_hamiltonian = molecule.get_molecular_hamiltonian(
    occupied_indices=range(active_space_start),
    active_indices=range(active_space_start, active_space_stop)
)

# Map operator to fermions and qubits.
fermion_hamiltonian = get_fermion_operator(molecular_hamiltonian)
qubit_hamiltonian = jordan_wigner(fermion_hamiltonian)
qubit_hamiltonian.compress()
print('The Jordan-Wigner Hamiltonian in canonical basis follows:\n{}'.format(qubit_hamiltonian))

# Get sparse operator and ground state energy.
sparse_hamiltonian = get_sparse_operator(qubit_hamiltonian).todense()
if True:
    energy, state = eigh(sparse_hamiltonian)
else:
    energy, state = eigsh(sparse_hamiltonian, 2, which='SA', maxiter=1e7)
print('Ground state energy before rotation is {} Hartree.\n'.format(energy[0]))
```
where eigsh branch always produce SIGSEGV while eigh always gave me reasonable eigenvectors.
what can be the problem of use eigsh?
my scipy version is 1.0.0

Best Vladimir.

**Comment by jarrodmcc** [comment]
This particular example seems to converge relatively fast (and correctly) in both cases for me.  To get to the root of this problem, can you tell me if eigsh work for you in other circumstances?  For example on just a simple 4x4 matrix? If you watch your resources, are you running out of memory when you get the SIGSEGV error?

**Comment by babbush** [comment]
This example runs just fine for me as well. Which version of OpenFermion are you running? What about your scipy version?

**Comment by Konjkov** [comment]
Hello Jarrod, Ryan
I have  scipy version 1.0.0 and eigsh never work fine for me even in _hydrogen_integration_test.py or _lih_integration_test.py where  eigsh is used in get_ground_state() function
Openfermion is latest from master (2 march commit)

best vladimir

**Comment by jarrodmcc** [comment]
Hi Vladimir
It sounds like the test is failing at the level of ARPACK.  If your python distribution was self-contained you may want to reinstall scipy and/or numpy.  If it's linking to existing linear algebra packages or ARPACK, you may need to reinstall those and ensure they are working.

**Comment by Konjkov** [comment]
Hi Jarrod
I created a simpler test that reproduces an issue on my computer
```
#!/usr/bin/env python3
import numpy as np
from scipy.sparse.linalg import eigsh

m = np.matrix(
[[-2.77555756e-17+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,   0.00000000e+00+0.j],
 [ 0.00000000e+00+0.j, -4.66581850e-01+0.j,  0.00000000e+00+0.j,   0.00000000e+00+0.j],
 [ 0.00000000e+00+0.j,  0.00000000e+00+0.j, -1.58557755e-01+0.j,   0.00000000e+00+0.j],
 [ 0.00000000e+00+0.j,  0.00000000e+00+0.j,  0.00000000e+00+0.j,  -4.66581850e-01+0.j]]
)
energy, state = eigsh(m, 2, which='SA', maxiter=1e7)
```

I think I need to write to scipy tech support, sorry.
