### ISSUE TITLE
issues in tutorial examples

### ISSUE THREAD

**Issue by michaelkaicher** [quantumlib/OpenFermion#252]
In "Basic OpenFermion example" in the tutorial there is an issue with

`from openfermion.ops import hermitian_conjugated`
I think it should be 
`from openfermion.utils import hermitian_conjugated`

**Comment by babbush** [comment]
Thanks for pointing this out Michael! Indeed, I don't think we've checked the code in the "examples" in a while. We do keep the "demo" up to date. I wonder if we shouldn't just remove the "tutorial" part of the docs and instead refer users to the jupyter notebook demo, which is both more comprehensive and more up-to-date. What do others think?

**Comment by conta877** [comment]
I agree that having a single place for people to go to as a reference is a good idea. 
That can also be the push to create better demos.

**Comment by kevinsung** [comment]
I agree that instead of the out-of-date examples section we should have a page with links to the demo notebooks on GitHub, at least for now.

**Comment by Strilanc** [comment]
I just wrote an execute-documentation-snippets-and-expect-it-to-pass test for another project. It should do a good job of catching these kinds of mistakes, though it comes with its own downsides. Does that sound interesting?

**Comment by kevinsung** [comment]
Sounds interesting to me! What are the downsides?

**Comment by babbush** [comment]
As nice as this would be, I think that our demos are much more pedagogical and complete anyways. I think we should just refer people there as a rule and remove the text tutorial.

**Comment by Strilanc** [comment]
The downside is that if you put expensive code into the documentation, your tests take forever. Also the doc code may touch the network, and other unfortunate things.

**Comment by babbush** [comment]
Closed by #292
