### ISSUE TITLE
Change normalization convention of Majorana operators

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#258]
Right now our convention is (a^\dagger + a) / sqrt(2), but I think omitting the normalization factor is more common in the literature and also more natural from a coding point of view (the coefficient can be passed to the function). I'd like to change the definition of Majorana operators to omit the normalization factor by default. People cool with that? @babbush? Not sure if anyone actually cares about this...

**Comment by babbush** [comment]
That's your class as far as I'm concerned. Go for it.

**Comment by jarrodmcc** [comment]
It seems like you are using it the most, so I would say that is fine.  If there are places where it is appropriate, maybe add a comment that we have chosen a particular normalization in that module, so it's clear that is a choice we have made rather than a given.
