### ISSUE TITLE
Import errors for function(s)

### ISSUE THREAD

**Issue by hsim13372** [quantumlib/OpenFermion#260]
Hello, I tried to use the function `jordan_wigner_interaction_op` from `openfermion.transforms` and kept running into an ImportError so I added the function to the` __init__.py` file in the openfermion.transforms subdirectory. I'm not sure if this was just an issue for me, or is this something to edit?

**Comment by kevinsung** [comment]
You should use `jordan_wigner` instead, which checks the types of the input operator and uses `jordan_wigner_interaction_op` as a helper function.

**Comment by hsim13372** [comment]
Ah I see. Thanks for the quick response!
