### ISSUE TITLE
Reorganization

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#271]
I think some reorganization is in order:
- I think `ops/__init__.py` should only import classes, and that the following moves make sense anyway:
-- `general_basis_change`, `prune_unused_indices`, `freeze_orbitals`, `normal_ordered` -> `utils/_operator_utils.py`.
-- `linearize_decoder` -> `transforms/_binary_codes.py`
- I think `transforms/_conversion.py` actually belongs in `utils`. It is the only file in `transforms` that is not actually concerned with fermionic transforms in the usual sense. If we put it in `utils` then we can also move the functions `jordan_wigner_sparse` and `qubit_operator_sparse` into it.

If people agree with these changes it would be best to make them before the next version release, and any help would be appreciated.

**Comment by babbush** [comment]
Fine with me

**Comment by idk3** [comment]
+1. My only concern is about this breaking some code (looks like only stuff in `_conversion.py` will be affected though really - is that right?)

**Comment by jarrodmcc** [comment]
One thing to ask is if the code has gotten developed and wide spread enough
that we should start phasing in 1 version deprecation warnings to help
people.  That is, when we move core functions, we leave something in place
for one version that calls the correct location with a printed or otherwise
raised warning that says "Deprecated in version ... in future use....".
Then remove that in the subsequent version.  This prevents people from
updating and suddenly having all their code not work with mysterious error
messages and having to hunt down the new location of the functions, as we
can't expect all users to follow our github discussions.

**Comment by babbush** [comment]
Indeed, I worry quite a lot about this.

**Comment by kevinsung** [comment]
It also might be good to leave in `isclose` with a DeprecationWarning for the next version (it was eliminated in #265 ).

**Comment by idk3** [comment]
+1 to all. Honestly though I would recommend leaving the deprecation warnings even longer than a single version - perhaps until we actually need to change them to something else.

But also along these lines we should be careful about how we handle warnings in other contexts (e.g. the h5py import warning from earlier in https://github.com/quantumlib/OpenFermion/issues/175 - we have to make sure to follow proper solutions like @babbush's there).

**Comment by jarrodmcc** [comment]
+1 to both of your thoughts on keeping them around for a little bit, adding
them for recent core functions, and using the official python "warning"
module to do them the right way.  We may also want a code style philosophy
that moves deprecated functions to the bottom of a file with an extra
comment line on expected removal dates etc?

Jarrod

**Comment by kevinsung** [comment]
Moving core functions seems to be pretty tricky. Take `normal_ordered` for instance. Right now it's in `ops` and I want to move it to `utils`. If we want to keep a deprecated version in `ops`, that version should also be named `normal_ordered`, which makes the behavior of something like `from openfermion import *` unpredictable (is it going to import the one from `ops` or the one from `utils`?) It might be possible to make this work by doing something complicated in the `__init__.py` files, but I don't know how.

It seems that what we really want to raise a warning for is simply the statement `from openfermion.ops import normal_ordered`. I don't know if it's possible to have this behavior though.

Another possibility is to just have the function available from both modules. What do people think of that?

**Comment by idk3** [comment]
I'm not sure I actually see the issue here - why can't `openfermion.ops.normal_ordered` just alias to `openfermion.utils.normal_ordered`? You'd have to remove `normal_ordered` from `ops`'s init but it should be OK otherwise, shouldn't it?

**Comment by kevinsung** [comment]
If we remove it from `ops/__init__.py`, then `openfermion.ops.normal_ordered` is no longer valid.

What I'm proposing is that we add to `ops/__init__.py` the statement `from openfermion.utils import normal_ordered`. But now that I think of it, that would cause a circular dependency!

**Comment by babbush** [comment]
My opinion is that we should leave these things where they are for now. If it isn't broken, let's not fix it. Especially not while we're making a bunch of other breaking changes. This is going to drive users crazy.

**Comment by kevinsung** [comment]
Sure, let's keep the core functions in place. Is it okay if I just move `prune_unused_indices`, `freeze_orbitals`, and `linearize_decoder` though?

**Comment by babbush** [comment]
Sure
