### ISSUE TITLE
ImportError: No module named openfermion.hamiltonians

### ISSUE THREAD

**Issue by SerkanGuldal** [quantumlib/OpenFermion#280]
I am trying to run on Fedora (Fedora release 27 (Twenty Seven)), but I have no success so far.
Everything is up to date.
I am receiving following error message

> Traceback (most recent call last):
  File "HH.py", line 1, in <module>
    from openfermion.hamiltonians import MolecularData
ImportError: No module named openfermion.hamiltonians

when I try to run the example: [example](https://github.com/quantumlib/OpenFermion/blob/master/examples/openfermion_demo.ipynb)

Many thanks in advance

**Comment by kevinsung** [comment]
What's the output of `pip show openfermion`?

**Comment by babbush** [comment]
This certainly looks like an install error.

**Comment by babbush** [comment]
I will close issue for now.

**Comment by SerkanGuldal** [comment]
Thank you. It seems you are right. After I have installed properly, it worked as expected. :)
