### ISSUE TITLE
Bug in Jordan Wigner for InteractionOperators

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#281]
Executing
```
from openfermion import *
from openfermion.utils._testing_utils import random_interaction_operator

iop = random_interaction_operator(5)
op1 = jordan_wigner(iop)
op2 = jordan_wigner(get_fermion_operator(iop))

assert op1 == op2
```
results in an AssertionError. That's a bug, right?

I suspect there's something wrong with how the indices are handled in `jordan_wigner_interaction_op`. A consistency test like this is actually not present in `transforms/_jordan_wigner_test.py`, though there are similar ones for the helper functions `jordan_wigner_one_body` and `jordan_wigner_two_body`.

**Comment by babbush** [comment]
Is the random interaction operator Hermitian? The specialized Jordan-Wigner code that works for InteractionOperators might expect that it is.

**Comment by kevinsung** [comment]
Yes, it is.

**Comment by babbush** [comment]
Hmm. It would be good (and perhaps difficult) to track down this bug. This routine is about 10X faster than first mapping to a FermionOperator and then mapping to qubits.

**Comment by kevinsung** [comment]
Here is a more damning indictment:
```
import os
from openfermion import *
from openfermion.config import DATA_DIRECTORY

geometry = [('Li', (0., 0., 0.)), ('H', (0., 0., 1.45))]
basis = 'sto-3g'
multiplicity = 1

filename = os.path.join(DATA_DIRECTORY, 'H1-Li1_sto-3g_singlet_1.45')
molecule = MolecularData(geometry, basis, multiplicity, filename=filename)
molecule.load()

iop = molecule.get_molecular_hamiltonian()
op1 = jordan_wigner(iop)
op2 = jordan_wigner(get_fermion_operator(iop))

assert op1 == op2
```
raises AssertionError.

Are there additional symmetries beside hermiticity that this function can take advantage of? Or should it work on a general Hermitian InteractionOperator?

**Comment by babbush** [comment]
the structure of the InteractionOperator already bakes in symmetries like particle number conservation. So yes, it should work with a general InteractionOperator.

**Comment by kevinsung** [comment]
I don't think the structure is enforced, however. For instance, if you initialize an InteractionOperator with some tensors that don't result in a Hermitian operator, it won't raise an error. So I guess I'm asking about what a "proper" InteractionOperator is; I know it must be Hermitian, but is there anything else? This is related to my PR #282 .

**Comment by babbush** [comment]
That's it basically.
