### ISSUE TITLE
[question] Is OpenFermion usable without the closed-source mosek?

### ISSUE THREAD

**Issue by yurivict** [quantumlib/OpenFermion#288]
OpenFermion depends on "cvxopt", and it in turn depends on "mosek", which is closed source.
On FreeBSD I can't install closed source libraries.
Does this mean that OpenFermion is unusable on FreeBSD?

**Comment by babbush** [comment]
I'll look into this tomorrow. The dependency on cvxopt can easily be removed if necessary - we use it only for the linear programming simplex routine.

**Comment by yurivict** [comment]
Actually, "mosek" is only an optional dependency of "cvxopt", so there is no real problem here.
Sorry for bothering! -)
