### ISSUE TITLE
Install problem in v0.4 with python-3.6

### ISSUE THREAD

**Issue by yurivict** [quantumlib/OpenFermion#289]
```
===>  Configuring for py36-OpenFermion-0.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 22, in <module>
    long_description = open('README.rst').read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6126: ordinal not in range(128)
```

Succeeds with python-2.7

**Comment by babbush** [comment]
Hmm, haven't seen this one before. You run into this while trying to install the develop branch?

**Comment by yurivict** [comment]
> You run into this while trying to install the develop branch?

No, it's with version 0.4.

**Comment by kevinsung** [comment]
@yurivict Would you mind trying again after replacing the line 
```
long_description = open('README.rst').read()
```
with
```
long_description = open('README.rst', encoding='utf-8').read()
```
in `setup.py`?

**Comment by kevinsung** [comment]
@yurivict wait... I just realized you can't do that if you're installing from `pip`; you'd need to get the source code (for instance, by cloning this repository) and install it from source.

**Comment by kevinsung** [comment]
The problem seems to be that on some systems (including @yurivict 's), Python uses the ASCII encoding by default to read files, but we probably didn't limit ourselves to a 128-character alphabet when writing the README. So perhaps we should update `setup.py` to explicitly specify reading with UTF-8 (by making the change I mentioned above.

**Comment by babbush** [comment]
If you make that change and Travis doesn't complain, I'll happily merge.

**Comment by yurivict** [comment]
> would you mind trying to install the develop branch and letting us know if @kevinsung 's PR solves your problem?


```
===>  Configuring for py27-OpenFermion-0.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 22, in <module>
    long_description = open('README.rst', encoding='utf-8').read()
TypeError: 'encoding' is an invalid keyword argument for this function
*** Error code 1
```

**Comment by kevinsung** [comment]
Wow it turns out that Python 2.7 does not support the `encoding` keyword argument to `open`. How did my PR pass Travis?!

**Comment by kevinsung** [comment]
Wait this can probably be fixed with `__future__`. Incoming PR...

**Comment by babbush** [comment]
@yurivict would you mind trying to install the develop branch one more time? PR #291 may have resolved it. I cannot replicate this error on my machine so your input is crucial.

**Comment by yurivict** [comment]
Yes, now the problem is gone.

**Comment by babbush** [comment]
Excellent we'll close the issue then. Thanks @kevinsung !
