### ISSUE TITLE
Does PolynomialTensor mistakenly implement __neq__ instead of __ne__?

### ISSUE THREAD

**Issue by singular-value** [quantumlib/OpenFermion#301]
Hey there, Pranav here. I'm hoping to get involved with OpenFermion, so I started taking a look at https://github.com/quantumlib/OpenFermion/issues/274 which seems like a good first issue (thanks @kevinsung and @idk3 for the clear description and background discussion).

I was reading through the code for `PolynomialTensor` and noticed that it implements a `__neq__` method. Should this method be `__ne__`? (https://docs.python.org/2/reference/datamodel.html#object.__ne__ and
https://docs.python.org/3/reference/datamodel.html#object.__ne__)

If so, I can submit a pull request.

**Comment by kevinsung** [comment]
Yes, you are correct. It would be great if you can fix that and test it better, perhaps using the EqualsTester utility in `utils/_testing_utils.py`.

**Comment by kevinsung** [comment]
Note that for the EqualsTester tests to pass you should set `__hash__` to `None` for PolynomialTensor. That's a change that should be made anyway.

**Comment by singular-value** [comment]
Resolved by pull request #303

**Comment by babbush** [comment]
@singular-value thanks for this contribution. If you'd like to be on the OpenFermion release paper, please email me at [my github name]@google.com and I can send you the link to our overleaf.
