### ISSUE TITLE
 H16_sto-3g_singlet_ring_0.7414.hdf5 does not have CC amplitudes

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion#302]
It seems like the H16 ring on the cloud library does not contain singles amplitudes as advertised.  

The following code prints `None` assuming the file 'H16_sto-3g_singlet_ring_0.7414.hdf5' is in the directory.
```
molefile = 'H16_sto-3g_singlet_ring_0.7414.hdf5'
molecule = MolecularData(filename=molefile)
print(molecule.ccsd_single_amps)
```
Which I think should load the amplitudes from the hdf5 file if the property `ccsd_single_amps` is `None`.

**Comment by babbush** [comment]
Glad to hear somebody is using the cloud library! Yeah if this works for the H15 ring but not the H16 ring I'd say that there is a problem. Want to help fix it?

**Comment by ncrubin** [comment]
I'd also guess CC calc didn't converge.  The `ccsd_energy` property is listed as `None` for H16.  For H15 the field is filled in.

**Comment by ncrubin** [comment]
Okay homework update.  Looks like FCI failed. Not the coupled-cluster calc (cc runs fast).  Restarting on another machine (with param adjustments) after I wipe off the burnt potato chip dust from my smoking laptop after that "small" fci calc.

**Comment by ncrubin** [comment]
@babbush I've completed the H16 calc.  The new file has all the advertised data--FCI, MP2, HF, CISD, CCSD and all integrals.  I've looked over the instructions on how to upload the file and it seems like I need an OpenFermion admin to send me a signed URL to the cloud library staging area.  Given that there is no change--other than correcting an existing calculation--a PR doesn't seem necessary (new commit would look exactly like head of master).  

I can upload the new files as soon as I have the correct endpoint.

**Comment by babbush** [comment]
@ncrubin I believe that @Spaceenter sent you the link a couple days ago. Did everything work okay?

**Comment by ncrubin** [comment]
Uploaded the file.  Did it make it?

**Comment by babbush** [comment]
Yep, it seems to be working now. Closing issue. Thanks Nick!
