### ISSUE TITLE
PEP8 vs Pylint

### ISSUE THREAD

**Issue by idk3** [quantumlib/OpenFermion#319]
@kevinsung pointed out some complaints raised by Pylint with my style changes in https://github.com/quantumlib/OpenFermion/pull/317 (lines with no assignment intended to raise errors). It might make sense to switch things over completely to Pylint instead of PEP8 - it has other features that might be helpful as well. Thoughts / objections?

**Comment by babbush** [comment]
interested to hear thoughts from @Strilanc

**Comment by kevinsung** [comment]
I think it would be good to have pylint run as part of continuous integration.

**Comment by babbush** [comment]
If you can setup pylint to run automatically as part of continuous integration then definitely do it. @Strilanc might have some idea how to do that. I would love this.

**Comment by josh146** [comment]
I agree with the move to Pylint, while linting with PEP8/pycodestyle, I noticed there were quite a few code issues it didn't pick up, which Pylint did. It's also pretty simple to integrate with Travis. Alternatively you can add a continuous-integration linting service like Codacy, which automates Pylint with pull requests.

**Comment by babbush** [comment]
I recently linted and noted about 150 violations throughout OpenFermion. I now consider this very high priority.

**Comment by kevinsung** [comment]
Looks like we've decided on a plan. Closing in favor of #416 .
