### ISSUE TITLE
Construct CSC matrix directly when creating sparse matrices

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#322]
While investigating the memory usage of some code that numerically calculates a ground state, e.g.
```
from openfermion import *

dimensions = 1
grid_length = 19
scale = 1.0
spinless = True

grid = Grid(dimensions, grid_length, scale)
model = jellium_model(grid, spinless=spinless, plane_wave=False)

hamiltonian_sparse = get_sparse_operator(model)
energies, states = scipy.sparse.linalg.eigsh(hamiltonian_sparse, k=1, which='SA')
```
I was surprised to find that the part of the code that uses the most memory is not the eigenvalue computation itself but the call to the function `get_sparse_operator`. By adding some print statements, I found that the line
```
sparse_operator = scipy.sparse.coo_matrix((
    values_list, (row_list, column_list)),
    shape=(n_hilbert, n_hilbert)).tocsc(copy=False)
```
in `utils/_jordan_wigner_sparse.py` causes memory usage to more than double compared to the rest of the code. I broke this statement down into two parts:
```
sparse_operator = scipy.sparse.coo_matrix((
    values_list, (row_list, column_list)),
    shape=(n_hilbert, n_hilbert))
sparse_operator = sparse_operator.tocsc(copy=False)
```
and found that it's the conversion from COO to CSC in the last line which is causing memory usage to double. Therefore, I think it would be nice if this code was rewritten to construct the CSC matrix directly, rather than first constructing a COO and then converting. This should be done everywhere we do such a thing, such as in the function `qubit_operator_sparse` too.

**Comment by jarrodmcc** [comment]
My personal feeling on this is that if someone is going to dedicate time to
writing the routine that directly constructs a particular sparse matrix
form for QubitOperators, that time would be better spent writing the
routine that performs the action of a qubit operator on a state vector
without constructing a matrix representation of the operator.  We've
desired that functionality for a while and I think it would make the
functionality you mention obsolete for use cases that are large enough for
this problem to matter.  It may actually be simpler code than constructing
the CSC or CSR matrix you mention directly too.  Because of the way python
loops so slowly it probably should be done using the numpy C API, cython or
something like that though, which may add a bit of complexity.

**Comment by kevinsung** [comment]
You're suggesting that we should implement something like `get_linear_operator` which returns a Scipy LinearOperator object? I think that's a good idea and would certainly satisfy my use case.

**Comment by jarrodmcc** [comment]
Yes exactly.  The basic functionality should operator exactly like SciPy
LinearOperator objects, and should conform to that standard so we can use
it with SciPy sparse diagonalization and exponentiation routines, but
perhaps doesn't need to be only that, i.e. can act without the need for
SciPy machinery as well.  This type of thing can be used as basic circuit
simulator functionality for testing without a specific plugin as well.

**Comment by idk3** [comment]
If it's useful, I wrote some code a while back related to this issue that gets the `LinearOperator` (with matrix-vector multiplication defined for it). My code does something a bit different / more basic than what we should really do - it offloads memory from the usual storage to disk, but it might still be useful or at least a useful starting point.

**Comment by kevinsung** [comment]
Closing this in favor of #324 .

**Comment by kevinsung** [comment]
I still need the sparse matrix in order to calculate expectation values of states, for instance from the output of a simulator.

**Comment by kevinsung** [comment]
Actually, #324 can also be used to calculate expectations.

**Comment by kevinsung** [comment]
Okay, I still need to get the sparse matrix if I want to compute the ground state within a particular particle number manifold by using jw_get_ground_states_by_particle_number. Can anyone think of a way to do this with a LinearOperator (or any other way that doesn't require computing the matrix)? It's easy to restrict a sparse matrix to a particular particle number manifold, but I don't see how to do that for a QubitOperator!

**Comment by babbush** [comment]
Yes it is very simple actually. Just seed the lanczos algorithm (what scipy
is doing) using the Linear Operator with a state that is explicitly in the
correct particle number manifold and it will only give you eigenstates that
are also in that manifold.

**Comment by kevinsung** [comment]
Wow, thanks. So `jw_get_ground_states_by_particle_number` should really be doing that then, since it is much more efficient than explicitly getting the restricted matrix, right?

**Comment by babbush** [comment]
Yes
