### ISSUE TITLE
Consistently use numpy arrays instead of sparse matrices for states

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#329]
@jarrodmcc has brought up something similar before, the main point being that using sparse matrices incurs a performance penalty and generally doesn't save space anyway because states will be dense. I also think this would be good because numpy and scipy always return numpy arrays for eigenvectors, so we wouldn't have to convert between datatypes to compare them.

I'm proposing that functions like `jw_get_gaussian_state`, `jw_hartree_fock_state`, and `jw_configuration_state` should return Numpy arrays instead of Scipy sparse matrices. @babbush is this too interface-breaking? It would be an easy change, and basically the only difference would be that states would have shape (N,) instead of (N, 1), which does not affect matrix-vector multiplication.

**Comment by kevinsung** [comment]
I just realized that `get_ground_state` already returns a Numpy array, so this would simply be making this behavior consistent.

**Comment by jarrodmcc** [comment]
I support this change

**Comment by babbush** [comment]
I do too then. Go for it.
