### ISSUE TITLE
error when using "get_ground_state()"

### ISSUE THREAD

**Issue by michaelkaicher** [quantumlib/OpenFermion#333]
Hi all, 
I constructed a Hamiltonian using FermionOperator following the "_hubbard.py" file, but for a different physical system. After turning this Hamiltonian into a sparse operator via "sparse = get_sparse_operator(Hamiltonian)" - which works fine - I tried to get the ground state using "get_ground_state(sparse)" I get the following error: 

> from ._conv import register_converters as _register_converters
Segmentation fault (core dumped)

Any ideas how to fix this? 
Cheers,
Michael

**Comment by babbush** [comment]
that seems like a problem with scipy. Perhaps try updating your scipy distribution? What version are you using?

Another thing to check is whether your Hamiltonian is actually Hermitian. Since the Lanczos algorithm expects a Hermitian matrix it can get pretty messed up if you pass it something else. There is some function somewhere in OpenFermion called "is_hermitian()" or something like that.

**Comment by michaelkaicher** [comment]
I'm using scipy version 1.0.1 and did already check whether my Hamiltonian is hertian via "is_hermitian()"- it is Hermitian. Updated latest numpy and scipy, still same error message as before.

**Comment by babbush** [comment]
hmm. Do you know if your Hamiltonian is degenerate? How many qubits is it? I suspect that this is a bug in the scipy lanczos routine. I would suspect this even more if the calculation succeeds for a smaller number of qubits.

**Comment by michaelkaicher** [comment]
basically for any number. I tried 5, 6 and 10 qubits

**Comment by babbush** [comment]
Sometimes Lanczos has problems when the system is degenerate. Can you do a dense diagonalization and see if that is the case?

**Comment by babbush** [comment]
Also, perhaps you can try seeding the get_ground_state function with a random vector as the guess?

**Comment by babbush** [comment]
Michael, I am going to close this issue for now since I do not believe the problem has to do with OpenFermion. If you wish to discuss further please feel free to reopen.
