### ISSUE TITLE
Write routine to produce transformation matrix for Hartree-Fock state

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#334]
A single-particle basis change matrix can easily be produced from a QuadraticHamiltonian instance by calling the method `diagonalizing_bogoliubov_transform`. It's not clear to me, however, how one could easily produce the necessary basis change matrix to describe a Hartree-Fock state. @babbush had some pointers on this:

>The challenge is simply to write a routine which, given a FermionOperator, computes the canonical orbitals by diagonalizing the Fock matrix and then expresses those orbitals as a linear combination of the original basis. For the case when one is just interested in state preparation, one is only concerned with constructing the occupied orbitals and so one does not need to diagonalize the Fock matrix and can instead use a variety of numerically cheaper methods.

**Comment by jarrodmcc** [comment]
After previous discussions we had, I realized I was actually ignoring the somewhat obvious solution to this problem, which is that PySCF, unlike other electronic structure codes, makes it very easy to install custom Hamiltonians and ask for solutions under various methods.  We actually only need to add one interface routine to our PySCF plugin that follows the example here:

http://sunqm.github.io/pyscf/advanced.html

under "custom Hamiltonian" and this will be essentially satisfied for the time being.  For reasonable sized systems it also provides a path for checking CCSD or DMRG energies in a relatively straightforward way.  The only thing this probably doesn't do is take advantage of known structures when we pass a diagonal Hamiltonian for example.

**Comment by babbush** [comment]
Hi Kevin. Even if @jarrodmcc review it previously, I am very worried about this design decision. First of all, we would normally like to think about the state preparation as adjustable and part of the variational algorithm. Second of all, if you have something called variational anstatz, which is actually a terrible variational ansatz by itself, people are going to use it improperly and get themselves into trouble. Also, I think we are abusing terminology here. I would absolutely consider the state prep as part of the ansatz. @jarrodmcc what do you think?
