### ISSUE TITLE
Support C-ish infrastructure

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#347]
It looks like the time has come. Parts of this are being discussed at #339 but it deserves its own issue, which is: how to support optimizations in a faster language such as C, C++, or Cython? I think we could simply have Cython be a dependency, but that requires a C compiler like `gcc` to be present on the system so making it be optional might be more involved.

**Comment by sheilaliuxl** [comment]
I have been doing some research on this, and here is a brief summary.
Cython is a superset of of Python, and its source code needs to go through 2 stages of compilation:
1. Compile Cython source code into platform independent C/ C++;
2. Compile generated C/ C++ source into a shared library with a standard C/ C++ compiler;

The standard approach for those 2 stages is:
1. `cythonize` from Cython;
2. `distutils` from **standard** Python library;

Eventually it goes back to *priority* of speeding up in scientific computations, which I'm not sure yet. @babbush 


References:
1. Cython: A Guide for Python Programmers [(link)](http://www.librarything.com/work/15650578/book/156090262).
2. [scipy](https://github.com/scipy/scipy) source code.

**Comment by babbush** [comment]
I think this is not currently urgent and it would be a very large project, so I'm going to close the issue. But thank you for this research Sheila.
