### ISSUE TITLE
Perhaps the README should indicate compatible python versions

### ISSUE THREAD

**Issue by DanielSank** [quantumlib/OpenFermion#35]

**Comment by babbush** [comment]
We support 2.7, 3.4, 3.5 and 3.6. So basically all of them (I don't think any of the other versions are really in use). We certainly can do this. I think a good option would be to add a badge showing the versions supported (for instance, this is done in [ProjectQ](https://github.com/ProjectQ-Framework/ProjectQ)). @Strilanc or @dabacon do you know how to add that badge?

**Comment by babbush** [comment]
Actually, @damiansteiger or @thomashaener can you comment on how to configure this badge? Since you guys set this up in ProjectQ you must know how to do it.

**Comment by dabacon** [comment]
Added badge.   This isn't pulling from anywhere specific, but using the custom badges from https://img.shields.io/
