### ISSUE TITLE
Adding Bayesian estimator for QPE

### ISSUE THREAD

**Issue by obriente** [quantumlib/OpenFermion#360]
Over the next few weeks I'll be adding some code to do Bayesian estimation for quantum phase estimation. This is part of a paper in production, along the lines of https://arxiv.org/abs/1508.00869 but with multiple qubits and experimental error.

If anyone wants to help with checking + approving code that would be much appreciated!

Cheers,

Tom.

**Comment by babbush** [comment]
@jarrodmcc and I have spoken with @obriente about this and we're looking forward to the PR!
