### ISSUE TITLE
does code of a 'simple' implementation of VQE already exist in OpenFermion?

### ISSUE THREAD

**Issue by michaelkaicher** [quantumlib/OpenFermion#392]
Hi all, 

besides the "_unitary_cc.py" file, I was wondering whether there is already code, which takes as input a reference state \rho_{init} = |\Psi_{ref}><\Psi_{ref}| as well as the Hamiltonian, the number of electrons and the number of spin-orbitals/qubits and then performs a VQE type optimization, outputting the optimized approximate ground state as well as the corresponding energy? 

Sry, if this has been asked before and it slipped my attention. 
Cheers, 
Michael.

**Comment by babbush** [comment]
Functionality for simulating VQE circuits fits within the scope of plugin libraries that combine with circuit composition frameworks (an example would be OpenFermion-ProjectQ or OpenFermion-Forest but those have limited functionality). In fact, the Google team will be launching a new plugin that does have the functionality you ask for very, very soon. We'll be sure to make this plugin visible from the front page as soon as its ready.
