### ISSUE TITLE
Create linalg module

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#406]
With Givens rotations, general basis change, commutators, BCH expansion.

This would be a breaking change.

**Comment by babbush** [comment]
This is not an acceptable name. Pretty much everything in quantum mechanics is linear algebra.

**Comment by kevinsung** [comment]
Cirq has a module called linalg which serves a very similar purpose.

**Comment by obriente** [comment]
Heh, just ran into this... We now have a linalg module, so I guess we can close this issue. (Ryan, if you still feel the same about the name let's discuss, I think the new naming system could use as much criticism as possible).
