### ISSUE TITLE
Remove "jw" prefix from functions in sparse_tools.py

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#411]
I think we should just assume the JWT is used. If we eventually support other options, this should be controlled by a function argument rather than having different functions.

This would be a breaking change.

**Comment by babbush** [comment]
No, I veto this suggestion. We shouldn't rename things completely on a whim, and this is not a good reason.

**Comment by babbush** [comment]
I think its important that people know we're using JW to get the sparse representation.
