### ISSUE TITLE
Move to pytest

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#414]
Writing tests with the `unittest` is a bit unwieldy. I'm not sure it's worth the effort to change all the tests to get rid of `unittest`, but we could do a gradual phase-out in which we rewrite AND improve tests. I think a lot of tests can be considerably simplified, for instance, by using EqualsTester and the random object generation utilities.

**Comment by babbush** [comment]
that's fine. I think we actually have (or had) an issue open about this somewhere?

**Comment by bryano** [comment]
I think we can just start using pytest without changing the code: https://docs.pytest.org/en/latest/unittest.html

**Comment by babbush** [comment]
this is redundant with #420
