### ISSUE TITLE
SymbolicOperator should be an abstract base class

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#415]
See https://docs.python.org/3/library/abc.html.

**Comment by babbush** [comment]
why?

**Comment by kevinsung** [comment]
- Requiring subclasses to explicitly specify the actions, their string representations, and whether different indices commute prevents mistakes. For instance, with the current setup one might define a class and forget to say that the different indices _do_ commute; then the class would be incorrectly defined.
- Conceptually, a SymbolicOperator with no defined actions doesn't really make sense. Yet, one can instantiate such a thing using `x = SymbolicOperator()`. Similarly, the default value of `different_indices_commute` is set to False, but this doesn't really make sense when there are no actions. Making it an abstract base class avoids these logical conundrums.

This would be a pretty minor change.

**Comment by babbush** [comment]
ok, sounds good.
