### ISSUE TITLE
Rename haar_random_vector to random_vector

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#417]
This function is useful in many situations where you don't really care about the particular distribution the vector is drawn from. In many use cases, the user who wants to generate random vectors might not even know what the Haar measure is. So I think it's nicer to just call the function `random_vector` and have in the documentation that it's drawn according to the Haar measure. @babbush

**Comment by babbush** [comment]
Kevin, I'm really against these minor name change issues. The library is not improved in any real sense by doing this but it is one more thing that could break people's code. Besides, I disagree that we should call it "random" vector. What does that mean? Is it it random with a flat distribution, with a Gaussian distribution? Is it real, complex? Etc.
