### ISSUE TITLE
rotate_basis should be a pure function

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#419]
The PolynomialTensor method `rotate_basis` changes the PolynomialTensor object in place. This behavior is inconsistent with our general approach (for example, in `_operator_utils.py`) to have functions that create a new operator as output. Often, one really does want to keep the original operator around. @jarrodmcc @babbush

**Comment by babbush** [comment]
I think the reason its like this is because we've only implemented basis rotations for certain 1- and 2-body types of operators. For instance, we haven't written code to do it for 3-body operators or higher.

**Comment by kevinsung** [comment]
I believe we did that in https://github.com/quantumlib/OpenFermion/pull/117.

**Comment by babbush** [comment]
Oh I guess so. Well in that case I support this change but we need to be careful to propagate the change to all dependancies since I believe that changing this will break OpenFermion-Psi4 and OpenFermion-PySCF. Let's not make this change until a big version bump (perhaps to v1.0) is imminent.

**Comment by ncrubin** [comment]
One can use `general_basis_transform` as a substitute which is standalone.
