### ISSUE TITLE
Move to pytest-cov

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#420]
The incremental coverage scripts used by Cirq and OpenFermion-Cirq are nice because you can use comments to indicate that certain lines don't need to be covered. I think we should move to that system and stop using coveralls. In the past we have had to override the coveralls status check many times.

**Comment by babbush** [comment]
That's fine. I feel like this is a bit redundant with #414. Also, I would deem all of this very low priority.
