### ISSUE TITLE
Make constructors and attributes of InteractionOperator and DiagonalCoulombHamiltonian more similar

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#428]
These two classes are quite similar so it would be nice to have them use the same attribute names and constructors. This would make it possible to write code that can simultaneously handle both kinds of operators. Also, why do I _have_ to specify the constant for InteractionOperator when I usually don't care what it is?

I want to change the constructor of InteractionOperator from
```
    def __init__(self, constant, one_body_tensor, two_body_tensor):
```
to
```
    def __init__(self, one_body, two_body, constant=0.0):
```
This would be a breaking change. Perhaps @babbush thinks this is trivial and totally unnecessary?

**Comment by babbush** [comment]
I think that this isn't a particularly good reason to make a breaking change and that to the extent it is, it is extremely low priority.
