### ISSUE TITLE
QubitOperator('X0 X0') should simplify to the identity

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#446]
Instead, it prints out to
```
1.0 [X0 X0]
```

**Comment by kevinsung** [comment]
There's a similar thing with FermionOperator, which is that `FermionOperator('0^ 0^')` does not simplify to zero. However, we have `normal_ordered` to simplify FermionOperators, while there is no analogous function for QubitOperators. But since simplifying QubitOperators is cheap (and normal-ordering is expensive), I think it makes sense to deal with this kind of stuff upon initialization.

**Comment by kevinsung** [comment]
Also, `QubitOperator('X0 Y0')` should simplify to `i Z0`.

**Comment by babbush** [comment]
I mean, if we're going to do this I guess it should be able to do arbitrary multiplication. E.g. it should know how to interpret "X0 Y1 Z3 X2 Z3 Y0", right?

**Comment by kevinsung** [comment]
Yeah.
