### ISSUE TITLE
Creating molecule pauli operator hamiltonians

### ISSUE THREAD

**Issue by bpcarlos** [quantumlib/OpenFermion#525]
Hello,
I would like to have the molecule pauli operator hamiltonians of several molecules in the minimal basis, ranging aprox from 14 to 20 qubits. Once I have the geometry of the molecule (from PubChem), how can I create its pauli operator hamiltonian? Thank you!

**Comment by ncrubin** [comment]
Hello @bpcarlos, please checkout the example ipython notebook for OpenFermion (https://github.com/quantumlib/OpenFermion/blob/master/examples/openfermion_tutorial.ipynb).  It walks through the basics of the library and how to do what you would like to do.  

If you find the examples are not clear feel free to raise an issue for better documentation and point out where we could improve.
