### ISSUE TITLE
bug in uccsd_singlet_generator

### ISSUE THREAD

**Issue by ggd87** [quantumlib/OpenFermion#533]
Hello,

I have been using the function uccsd_singlet_generator in utils/_unitary_cc.py and noticed that at line 308 there is the for loop 

```
        for (spin_a, spin_b) in itertools.product(range(2), repeat=2):
            # Get the functions which map a spatial orbital index to a
            # spin orbital index
            index_a = spin_index_functions[spin_a]
            index_b = spin_index_functions[spin_b]

            # Get indices of spin orbitals
            virtual_1_a = index_a(virtual_spatial_1)
            occupied_1_a = index_a(occupied_spatial_1)
            virtual_2_b = index_b(virtual_spatial_2)
            occupied_2_b = index_b(occupied_spatial_2)
```

which will include values where spin_a = spin_b, hence the spin orbitals virtual_1_a = virtual_2_b, or occupied_1_a = occupied_2_b. I don't think there should be excitations in which like spins are excited to/from the same spatial orbital. This doesn't affect the results (as the corresponding amplitudes invariably go to 0 for singlets), but this would add unnecessary terms to the cluster operator, hence it will affect efficiency. 

I made a copy of this function in which I simply added conditionals that throw out excitations involving those spin orbitals, and I get the same answer with fewer terms in the cluster operator.

```
        for (spin_a, spin_b) in itertools.product(range(2), repeat=2):
            # Get the functions which map a spatial orbital index to a
            # spin orbital index
            index_a = spin_index_functions[spin_a]
            index_b = spin_index_functions[spin_b]

            # Get indices of spin orbitals
            virtual_1_a = index_a(virtual_spatial_1)
            occupied_1_a = index_a(occupied_spatial_1)
            virtual_2_b = index_b(virtual_spatial_2)
            occupied_2_b = index_b(occupied_spatial_2)

            if virtual_1_a == virtual_2_b:
                continue
            if occupied_1_a == occupied_2_b:
                continue
            else:

                generator += FermionOperator((
                    (virtual_1_a, 1),
                    (occupied_1_a, 0),
                    (virtual_2_b, 1),
                    (occupied_2_b, 0)),
                    coeff)
                if anti_hermitian:
                    generator += FermionOperator((
                        (occupied_2_b, 1),
                        (virtual_2_b, 0),
                        (occupied_1_a, 1),
                        (virtual_1_a, 0)),
                        -coeff)

    return generator 
```

It looks like there may be a similar bug is also in uccsd_singlet_get_packed_amplitudes, around line 190-203 of utils/_unitary_cc.py.

Thanks,
Gabriel

**Comment by ncrubin** [comment]
Hi Gabriel,

Thanks for pointing this out.  It is true that this is a redundancy.  Calling normal_order on the fermion operator also would have removed the terms in the generator that are automatically zero (but with extra computational cost!).  Would you like to open a PR with this fix?

**Comment by ggd87** [comment]
Hi Nicholas,

I sent a pull request for this. I will close the issue now.

Thanks again,
Gabriel
