### ISSUE TITLE
Implement get_majorana 

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion#542]
We've had Majorana operators in OpenFermion for awhile now.  It would be great to have transformation functions from a FermionOperator to MajoranaOperator.  

I would imagine there could be a simple substitution function that maps FermionOperators to their Majorana representation.  Maybe a more efficient implementation for tensor representation of FermionOperators would be doing the basis rotation associated with going to the Majorana representation.  See (https://arxiv.org/abs/1711.05395) for details.

**Comment by jitendrs** [comment]
@ncrubin can you please assign it to me.

**Comment by GopiKishan14** [comment]
@ncrubin can you please assign this to me also?

**Comment by kevinsung** [comment]
@GopiKishan14 To avoid duplication of effort we should have one person working on this at a time, unless you collaborate.

**Comment by StefanoPolla** [comment]
I've been working with MajoranaOperator, using custom functions for now. What's the status of this?

**Comment by jitendrs** [comment]
@kevinsung can you please assign it to someone else. Apologies for such notice request.

**Comment by StefanoPolla** [comment]
I'm happy to take it
@ncrubin, @kevinsung can you assign it to me?

**Comment by ncrubin** [comment]
Implemented by #589
