### ISSUE TITLE
HDF5 Issue on install?

### ISSUE THREAD

**Issue by hellmersjl3ds** [quantumlib/OpenFermion#543]
When doing a developers install of OpenFermi I'm getting a message

error: libhdf5.so: cannot open shared object file: No such file or directory

Do I need to install something manually?

I'm installing on Red Hat 7.  Using Miniconda for my Python environment.  I've created a virtual environment for OpenFermion

BTW I tried it on Windows, with Anaconda as the Python management systems, and it worked fine. 

Complete error message.

Collecting more-itertools
  Downloading https://files.pythonhosted.org/packages/45/dc/3241eef99eb45f1def35cf93af35d1cf9ef4c0991792583b8f33ea41b092/more_itertools-7.2.0-py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 735kB/s 
Building wheels for collected packages: h5py, future, matplotlib, pubchempy, tornado, prometheus-client, pandocfilters, pyrsistent, backcall, MarkupSafe
  Building wheel for h5py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/jhellmers/miniconda3/envs/quantumlib/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vuo41red/h5py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vuo41red/h5py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mo1gpo3s --python-tag cp38
       cwd: /tmp/pip-install-vuo41red/h5py/
  Complete output (64 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/h5py
  copying h5py/__init__.py -> build/lib.linux-x86_64-3.8/h5py
  copying h5py/h5py_warnings.py -> build/lib.linux-x86_64-3.8/h5py
  copying h5py/highlevel.py -> build/lib.linux-x86_64-3.8/h5py
  copying h5py/ipy_completer.py -> build/lib.linux-x86_64-3.8/h5py
  copying h5py/version.py -> build/lib.linux-x86_64-3.8/h5py
  creating build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/base.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/compat.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/dims.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/files.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/filters.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/group.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/selections.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  copying h5py/_hl/vds.py -> build/lib.linux-x86_64-3.8/h5py/_hl
  creating build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/__init__.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/common.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_attribute_create.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_attrs.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_attrs_data.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_base.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_completions.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_dataset.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_dataset_getitem.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_dataset_swmr.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_datatype.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_deprecation.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_dimension_scales.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_dtype.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_file.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_file2.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_file_image.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_filters.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_group.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_h5.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_h5d_direct_chunk.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_h5f.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_h5p.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_h5pl.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_h5t.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_objects.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_selections.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_slicing.py -> build/lib.linux-x86_64-3.8/h5py/tests
  copying h5py/tests/test_threads.py -> build/lib.linux-x86_64-3.8/h5py/tests
  creating build/lib.linux-x86_64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/__init__.py -> build/lib.linux-x86_64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_highlevel_vds.py -> build/lib.linux-x86_64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_lowlevel_vds.py -> build/lib.linux-x86_64-3.8/h5py/tests/test_vds
  copying h5py/tests/test_vds/test_virtual_source.py -> build/lib.linux-x86_64-3.8/h5py/tests/test_vds
  running build_ext
  Loading library to get version: libhdf5.so
  error: libhdf5.so: cannot open shared object file: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for h5py

**Comment by kevinsung** [comment]
Can you try running just `pip install h5py` in a clean virtual environment?

**Comment by hellmersjl3ds** [comment]
That worked fine.

(testhdf5) [jhellmers@quantum qcnotebooks]$ pip install h5py
Collecting h5py
  Downloading https://files.pythonhosted.org/packages/60/06/cafdd44889200e5438b897388f3075b52a8ef01f28a17366d91de0fa2d05/h5py-2.10.0-cp36-cp36m-manylinux1_x86_64.whl (2.9MB)
     |████████████████████████████████| 2.9MB 6.6MB/s 
Collecting numpy>=1.7
  Downloading https://files.pythonhosted.org/packages/d2/ab/43e678759326f728de861edbef34b8e2ad1b1490505f20e0d1f0716c3bf4/numpy-1.17.4-cp36-cp36m-manylinux1_x86_64.whl (20.0MB)
     |████████████████████████████████| 20.0MB 30kB/s 
Collecting six
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, h5py
Successfully installed h5py-2.10.0 numpy-1.17.4 six-1.13.0

**Comment by kevinsung** [comment]
@hellmersjl3ds In the environment in which you are unable to install openfermion, are you able to install h5py by itself? What happens if you do that, and then try to install openfermion?

**Comment by ncrubin** [comment]
closed due to inactivity.
