### ISSUE TITLE
error in installing forest openfermion

### ISSUE THREAD

**Issue by misz3540** [quantumlib/OpenFermion#547]
Hi. I tried installing forestopenfermion by
pip install forestopenfermion

And, i got the following long error message (cut):
Building wheels for collected packages: scipy
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/michelle/anaconda/envs/py3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jl/jdqt56zx7nl6czhgp8qhdwd40000gn/T/pip-install-7odaoj4r/scipy/setup.py'"'"'; __file__='"'"'/private/var/folders/jl/jdqt56zx7nl6czhgp8qhdwd40000gn/T/pip-install-7odaoj4r/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/jl/jdqt56zx7nl6czhgp8qhdwd40000gn/T/pip-wheel-8zcv76y9 --python-tag cp37
       cwd: /private/var/folders/jl/jdqt56zx7nl6czhgp8qhdwd40000gn/T/pip-install-7odaoj4r/scipy/
  Complete output (1015 lines):
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/michelle/anaconda/envs/py3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/michelle/anaconda/envs/py3/include']
  
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/michelle/anaconda/envs/py3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/michelle/anaconda/envs/py3/include']
  
  Running from scipy source directory.
  non-existing path in 'scipy/integrate': 'quadpack.h'
  Splitting linalg.interpolative Fortran source files
  blas_opt_info:
  blas_mkl_info:
  customize UnixCCompiler
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/michelle/anaconda/envs/py3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/michelle/anaconda/envs/py3/include']
  
    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/michelle/anaconda/envs/py3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/michelle/anaconda/envs/py3/include']
  
  non-existing path in 'scipy/sparse': 'sparsetools/sparsetools_impl.h'
  non-existing path in 'scipy/sparse': 'sparsetools/bsr_impl.h'
  non-existing path in 'scipy/sparse': 'sparsetools/csc_impl.h'
  non-existing path in 'scipy/sparse': 'sparsetools/csr_impl.h'
  non-existing path in 'scipy/sparse': 'sparsetools/other_impl.h'
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  creating build
  creating build/src.macosx-10.9-x86_64-3.7
  creating build/src.macosx-10.9-x86_64-3.7/scipy
  building library "dfftpack" sources
  building library "fftpack" sources
  building library "mach" sources
  building library "quadpack" sources
  building library "odepack" sources
  building library "dop" sources
  building library "fitpack" sources
  building library "fwrappers" sources
  building library "odrpack" sources
  building library "minpack" sources
  building library "rootfind" sources
  building library "superlu_src" sources
  building library "arpack_scipy" sources
  building library "sc_c_misc" sources
  building library "sc_cephes" sources
  building library "sc_mach" sources
  building library "sc_amos" sources
  building library "sc_cdf" sources
  building library "sc_specfun" sources
  building library "statlib" sources
  building extension "scipy.cluster._vq" sources
  building extension "scipy.cluster._hierarchy" sources
  building extension "scipy.fftpack._fftpack" sources
  creating build/src.macosx-10.9-x86_64-3.7/scipy/fftpack
  creating build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src
  conv_template:> build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src/dct.c
  conv_template:> build/src.macosx-10.9-x86_64-3.7/scipy/fftpack/src/dst.c
  f2py options: []
  f2py: scipy/fftpack/fftpack.pyf
  Reading fortran codes...
  	Reading file 'scipy/fftpack/fftpack.pyf' (format:free)
  Line #86 in scipy/fftpack/fftpack.pyf:"       /* Single precision version */ "
  	crackline:2: No pattern for line
  Post-processing...

and so on... Could somebody help me... Thanks!

**Comment by babbush** [comment]
Hey there. I would recommend posting this as an issue on Forest-OpenFermion's GitHub (https://github.com/rigetti/forest-openfermion). Though affiliated, a different group of people maintain that package. Accordingly, I will close this issue on OpenFermion. Good luck!
