### ISSUE TITLE
Remove python 2 from .travis.yml

### ISSUE THREAD

**Issue by vtomole** [quantumlib/OpenFermion#550]
Python 2 is passed "end of life": https://pythonclock.org/

**Comment by kevinsung** [comment]
This means we would be dropping support for Python 2 altogether. At the last OpenFermion sync everyone was on board. So unless @babbush or @jarrodmcc have any objections, let's go ahead with dropping Python 2 support.

**Comment by ncrubin** [comment]
Done by #574
