### ISSUE TITLE
How to pad a dense representation of an operator so as to span the full Hilbert space properly?

### ISSUE THREAD

**Issue by hariseldon99** [quantumlib/OpenFermion#553]
OK. Suppose I have a lattice of spinful fermions with, say, 4 sites (nsites = 4). The Hilbert space should have dimension 4^4 = 256. Any operator in this space should have a matrix representation that is of size 256 X 256.

If I want to create an operator like
<img src="https://latex.codecogs.com/gif.latex?num\_init&space;=&space;\sum_{j&space;\in&space;occupied\_upspins}&space;\left[&space;c^\dagger_{j\uparrow}&space;c_{j\uparrow}&space;&plus;&space;c^\dagger_{j\downarrow}&space;c_{j\downarrow}&space;\right]" title="num\_init = \sum_{j \in occupied\_upspins} \left[ c^\dagger_{j\uparrow} c_{j\uparrow} + c^\dagger_{j\downarrow} c_{j\downarrow} \right]" />

where occupied_upspins = np.array([0, 1]) (suppose, purely arbit choice), and I do an iterable of FermionOperator() calls over the up_indices of occupied_upspins, then get a dense representation with get_sparse_operator(num_init_sym).todense(), I actually get a 16 X 16 matrix. Presumably, this is the submatrix of the occupied states only, and all I have to do is pad the extra dimensions with zeroes to get it up to 256 X 256.

I pad it like so:
num_init = np.pad(num_init, [(0, 256-16), (0, 256-16)], mode='constant')

Now, I seek to compute the expectation value wrt the corresponding eigenstate, which *should* be nonzero. If I get the eigenstate from jw_configuration_state(occupied_upspins, 2 * nsites).flatten() and do numpy.multi_dot, I get 0 as the value instead.

Am I padding it wrong?

I have the code below:

```python
import numpy as np
from numpy.linalg import multi_dot
from openfermion.ops import FermionOperator, down_index, up_index
from openfermion.transforms import get_sparse_operator
from openfermion.utils import jw_configuration_state

nsites = 4
occupied_upspins = np.array([0, 1])

num_init_sym = FermionOperator()
for i in range(nsites):
        iup, idn = up_index(i), down_index(i)
        coeff = 1. if i in occupied_upspins else 0.
        num_init_sym += FermionOperator(((iup, 1), (iup, 0)), coeff) + \
                                                                                        FermionOperator(((idn, 1), (idn, 0)), coeff)

numstate = jw_configuration_state(occupied_upspins, 2 * nsites).flatten()
numstate_a = numstate + (1j) * np.zeros(4**nsites) # This is stupid but apparently necessary


num_init = get_sparse_operator(num_init_sym).todense()
num_init = np.asarray(num_init)


full = numstate.size
red, _ = num_init.shape
num_init = np.pad(num_init, [(0, full-red), (0, full-red)], mode='constant')


expectation = multi_dot([numstate.conjugate(), num_init, numstate])
print(expectation)
```

**Comment by kevinsung** [comment]
Indeed, you are padding it wrong. Instead of padding the extra dimensions with zeros, you should be tensoring with the identity. So the line
```
num_init = np.pad(num_init, [(0, full-red), (0, full-red)], mode='constant')
```
should be replaced with
```
num_init = np.kron(num_init, np.eye(full // red))
```
After this change, the output is 2 instead of 0. If you were expecting 4, that's because when you used `jw_configuration_state`, you forgot to expand the sites into their up and down components. So the line
```
numstate = jw_configuration_state(occupied_upspins, 2 * nsites).flatten()
```
should be replaced with
```
occupied_indices = [up_index(i) for i in occupied_upspins] + [down_index(i) for i in occupied_upspins]
numstate = jw_configuration_state(occupied_indices, 2 * nsites).flatten()
```
After this change, the output is 4.

**Comment by ncrubin** [comment]
you can also specify the number of qubits `n_qubits` you want in the `get_sparse_operator'.   This will enforce that you are lifted to the appropriate size space.
