### ISSUE TITLE
Read the Docs broken

### ISSUE THREAD

**Issue by bryano** [quantumlib/OpenFermion#568]
The [Read the Docs site](https://openfermion.readthedocs.io/en/latest/index.html) only displays the submodules and nothing else. Same is true for the [PDF version](https://openfermion.readthedocs.io/_/downloads/en/latest/pdf/), which implies that it's not just a browser issue. (I'm using Chrome version 80 on Ubuntu.) Searching for anything (on the RTD site) yields no results.

**Comment by kevinsung** [comment]
Hmm the docs are building locally for me.

**Comment by kevinsung** [comment]
I switched Read the Docs to use Python 3 instead of Python 2 and now the docs build fine.
