### ISSUE TITLE
Add auto-merge bot

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#578]

**Comment by ncrubin** [comment]
@kevinsung is this auto-merge upon reviewers sign-off?

**Comment by vtomole** [comment]
It automerges once a label is added to the PR.

**Comment by kevinsung** [comment]
Yeah, reviews are marked for auto-merge by adding a label, and it only works after the PR has been approved and passes CI.

**Comment by fdmalone** [comment]
This is done via github now.
