### ISSUE TITLE
usr/openfermion/examples/ is not allowed in Filesystem Hierarchy Standard  2.3

### ISSUE THREAD

**Issue by kevinsmia1939** [quantumlib/OpenFermion#590]
Hello,

I tried to build openfermion on linux openSUSE Tumbleweed.

I noticed that there are files that were placed in usr/openfermion/.
This location are discourage and should be avoid. 

Thanks.

```
 RPMLINT report:
[   39s] ===============
[   40s] python3-openfermion.noarch: W: suse-filelist-forbidden-fhs23 /usr/openfermion is not allowed in FHS 2.3
[   40s] see http://www.pathname.com/fhs/ for a better location
[   40s] 
[   40s] 2 packages and 0 specfiles checked; 0 errors, 1 warnings
```

**Comment by kevinsung** [comment]
Can you tell us what commands you used to produce that output?

**Comment by kevinsmia1939** [comment]
> Can you tell us what commands you used to produce that output?

Hello,

I use openSUSE build service which can build package from source code.
This is the repository I made for openfermion.
https://build.opensuse.org/package/show/home:andythe_great/python-openfermion

Here is the .spec file which contain instruction to build the package from source.
https://build.opensuse.org/package/view_file/home:andythe_great/python-openfermion/python-openfermion.spec?expand=1

Here is the RPMLINT output that you see.
https://build.opensuse.org/package/live_build_log/home:andythe_great/python-openfermion/openSUSE_Tumbleweed/x86_64

**Comment by ncrubin** [comment]
@kevinsmia1939 to my knowledge we don't explicitly put any files in /usr/openfermion.  I'm not familiar with this build system so I can't even guess why you are hitting this particular problem.  Has this come up with any other python projects and this build system?

**Comment by kevinsmia1939** [comment]
> @kevinsmia1939 to my knowledge we don't explicitly put any files in /usr/openfermion. I'm not familiar with this build system so I can't even guess why you are hitting this particular problem. Has this come up with any other python projects and this build system?

I have a feeling that if the data_files is not given a directory, it would go to /usr/ by default?
Does it need to have a (directory, files) pair to get install to a correct directory?
https://docs.python.org/2.5/dist/node13.html

https://github.com/quantumlib/OpenFermion/blob/be2a39f1e7aa1262a665d2e5ad0d4f6bbfad23a2/setup.py#L51

**Comment by mpharrigan** [comment]
At present, we only officially support installation via `pip`, and we follow normal Python packaging guidelines for `setup.py`. We strongly encourage the use of a virtual environment to avoid polluting system directories.

It's great that you're packaging this up for a linux distro! We'll accept any patches that makes your life easier and doesn't interfere with normal installation into a python virtualenv.
