### ISSUE TITLE
Move to one branch git flow

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#6]
We have decided that we will move away from the master/develop style git flow and just have a master branch. The master branch should always be a stable build but every once and a while if there is a lot of development we will tag a new release, bump the version number, and update PyPI.

Craig, can you take care of this? The idea should be to somehow delete master and then rename develop as master without losing any of the commit history in develop. Can it be done?

**Comment by maffoo** [comment]
+1 for master-based workflow. @babbush you can just force-push the current `develop` branch to `master`; that would erase any history on the current master branch and just replace it with the develop branch. Since @Strilanc is out at the moment, I'd be happy to help with this.

**Comment by babbush** [comment]
@maffoo that would be great! Thank you! If it is not too much trouble, can you do this for the other repos as well? You can ignore the pull request to master on OpenFermion-ProjectQ since I was just pulling develop to master anyways. I assume this won't hurt my pull request that is open on OpenFermion?

**Comment by maffoo** [comment]
@babbush, I'll force-push the develop branch to master and then see if we can update your PR to merge into master instead. If it can't be updated in-place we might have to open a new PR.

**Comment by babbush** [comment]
:+1:

**Comment by maffoo** [comment]
Ok, I force-pushed master and changed the PR base on #5 to point to master so should be good. I also re-enabled branch protection on master and changed the repository default branch to master. Changing the default branch caused github to pop up a warning dialog about possible strangeness for forked repos and clones. If people run into any issues please comment on this issue and we'll figure it out.

**Comment by maffoo** [comment]
Looks like if you have cloned the repo locally you will want to change the file `.get/HEAD` to point to the correct branch. This file probably looks like
```
ref: refs/head/develop
```
and should be changed to
```
ref: refs/head/master
```
Alternatively, you can just delete your local checkout and clone again from github (make sure to push any in-progress work on other branches to github so you don't lose it).

If you have a fork of the repo, you have two options:
1. Make the same changes in your fork as we've done here, e.g. force-push the develop branch to master, make master the default branch, and change `.git/HEAD` on any local checkouts.
2. Delete your fork and create a new fork, so the fork will be set up to match the new default branch structure. As above, you'll need to take care to save any in-progress work before doing this.

**Comment by maffoo** [comment]
Pushed master and updated the default branch on the other repos.

**Comment by babbush** [comment]
Thanks Matthew!!
