### ISSUE TITLE
QubitOperator to PauliSum Conversion

### ISSUE THREAD

**Issue by tanujkhattar** [quantumlib/OpenFermion#618]
[`openfermion.QubitOperator`](https://github.com/quantumlib/OpenFermion/blob/302449a45ef0106a1ac210174ddefc2b7ffb71a6/src/openfermion/ops/_qubit_operator.py#L39) and [`cirq.PauliSum`](https://github.com/tanujkhattar/Cirq/blob/4df6919aae05f4ea6a2dd164fc846078db6b6bb0/cirq/ops/linear_combinations.py#L298) represent the same logical entity, i.e. A linear combination of Pauli Terms.      

Since there is now a general consensus on removing the constraint to keep OpenFermion independent of Cirq (for eg: The Openfermion-Cirq, Openfermion integration), I propose that:

1. We should provide a way to convert `QubitOperator` to `PauliSum`. For eg, using a helper `qubit_operator_to_pauli_sum`.

2. In the long run, should we also aim to get rid of the duplicate pieces and adopt the `QubitOperator` to internally use PauliSum structure (need discussion here)? 

For 1, there is a clear short term advantage because this conversion helps us use many nice features in cirq like `PauliSumCollector` etc. 

For example, Given an `ansatz_circuit` and a `qubit_hamiltonian`, we can write a simple function to find the optimal parameters for the `ansatz_circuit` to minimise expected value of `qubit_hamiltonian` as follows:
```python
def qubit_operator_to_pauli_sum(qubit_operator, qubits):
  # This helper (or another equivalent) should be a part of openfermion. 
  qubit_list = [*qubits]
  pauli_strings = []
  for term, coeff in qubit_operator.terms.items():
    pauli_string_contents = {}
    for qub, pau in term:
      pauli_string_contents.update({qubit_list[qub] : pau})
    pauli_strings.append(cirq.PauliString(pauli_string_contents, coefficient=coeff))
  return cirq.PauliSum.from_pauli_strings(pauli_strings)

def optimize_circuit(ansatz_circuit, qubit_hamiltonian, qubits):
  # Assuming ansatz_circuit has a single parameter theta_1.
  pauli_sum_hamiltonian = qubit_operator_to_pauli_sum(qubit_hamiltonian, qubits)
  def func(x):
    p = cirq.PauliSumCollector(circuit=cirq.resolve_parameters(ansatz_circuit, {'theta_1' : x[0]}),
                              observable=pauli_sum_hamiltonian,
                              samples_per_term=20000)
    p.collect(sampler=cirq.Simulator())
    return p.estimated_energy()

  return scipy.optimize.minimize(func, numpy.random.rand(1), tol = 1e-9, method = 'COBYLA')
```

Please let me know your thoughts/concerns and I can proceed with a PR accordingly.

**Comment by tanujkhattar** [comment]
@ncrubin

**Comment by ncrubin** [comment]
Hi @tanujkhattar, please coordinate with @kevinsung on this larger effort.  I am not in a rush to do this integration especially since cirq is moving quickly to 1.0 and could have significant feature changes.

**Comment by tanujkhattar** [comment]
Thanks for pointing out the earlier efforts in this direction. I've left some comments on your PR. Will mark this issue as duplicate and close it. Thanks!
