### ISSUE TITLE
Update documentation with new organization

### ISSUE THREAD

**Issue by xabomon** [quantumlib/OpenFermion#626]
I have been looking at the documentation and it does not seem to be updated with respect to the new organization of OF.

**Comment by ncrubin** [comment]
This is very true!  @xabomon please feel free to point out specifics for where we can improve the docs.  The docs upgrade is very important and more input the better!

**Comment by ncrubin** [comment]
I've added issue #636 which is the start of this process.

**Comment by ncrubin** [comment]
new docs website and reorg takes care of this....though further documentation and tutorials are always needed!
