### ISSUE TITLE
Colab instead of Binder?

### ISSUE THREAD

**Issue by balopat** [quantumlib/OpenFermion#628]
I've been thinking about a unified way of running notebooks easily in Cirq as well as OpenFermion. I saw the binder link - initially I liked it but then I opened it and it takes way too long to bring up the container (5+ minutes). 

What do you think about using Colab? 

https://colab.research.google.com/github/quantumlib/OpenFermion

It is much faster - but you'll need a Google account as soon as you want to run anything. 
Also you'll need to add in all notebooks the `!pip install openfermion` command at the beginning with clear instructions that it's only for colab.

**Comment by babbush** [comment]
When you say that you'll need a Google account to run anything - do you mean just a gmail for instance? That requirement isn't ideal but I suppose most people have a gmail at this point. It seems like a reasonable price to pay for the faster execution. Can anyone think of any other downsides we should consider?

**Comment by balopat** [comment]
> When you say that you'll need a Google account to run anything - do you mean just a gmail for instance? That requirement isn't ideal but I suppose most people have a gmail at this point. It seems like a reasonable price to pay for the faster execution.

Yes, a gmail account works. Agreed!

**Comment by ncrubin** [comment]
I think the price of having a google account is small in comparison to the 5 minute load time of binder.  I'm pro colab transition.

**Comment by balopat** [comment]
Great! We can also put a colab detection logic for installation on top of the notebooks.

```
import sys
if `google.colab' in sys.modules: 
  !pip install openfermion --quiet
```

This way they can still work in a local jupyter env as well. 
Happy to raise a PR for this.
