### ISSUE TITLE
Requirement clash with Cirq master

### ISSUE THREAD

**Issue by xabomon** [quantumlib/OpenFermion#639]
Hi team,

Installing master branch of Cirq raises an error with requirement of cirq==0.8.2.

Is there a good or easy way to sync releases?

**Comment by kevinsung** [comment]
Depending on the master branch of Cirq is not a good idea because that exposes us to breaking changes in a way we cannot control. Our strategy is to depend on a version of Cirq that has been released on PyPI; that way we can sync up with Cirq all at once, when we choose to.

**Comment by xabomon** [comment]
Hi @kevinsung 

Thanks for the answer, that actually makes sense because I was installing Cirq from master and not from the PyPI released branch.

I will close the issue.
