### ISSUE TITLE
Can't pip install from git

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion#644]
```
pip install git+https://github.com/quantumlib/OpenFermion.git@master#egg=openfermion
```

Throws an error:

```
[Lots elided output]
running install_data
error: can't copy 'docs/tutorials/binary_code_transforms_demo.ipynb': doesn't exist or not a regular file
```

@lamberta has this come up before in moving docs around?

**Comment by ncrubin** [comment]
Might be related to data_files field in setup.py is no longer working with wheels

https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=data_files

**Comment by lamberta** [comment]
Looks like I neglected to update the basename of the file in setup.py when I moved/renamed a few tutorials. So these filenames should match the filenames in the [docs/tutorials/](https://github.com/quantumlib/OpenFermion/tree/master/docs/tutorials) directory, e.g. `docs/tutorials/binary_code_transforms.ipynb`.

These were in `/examples`. Do you need to install them with the pip package?

**Comment by ncrubin** [comment]
I don't see a reason to install them with the package but we were doing that before.  Maybe a user could reference the notebook after they do a pip install to see how something works?  I think the docs should serve that purpose not the notebook.  Let's keep it in the install for now and I'll bring up the topic of deletion at the next openfermion-sync.  I don't think cirq installs their tutorials.  

Can you make the appropriate change in the `setup.py` file to fix this?
