### ISSUE TITLE
Get a matrix representation of QubitOperator command 

### ISSUE THREAD

**Issue by zohimchandani** [quantumlib/OpenFermion#646]
I have some code which looks like this: 

```
 psi = (disc_weights[0] * QubitOperator('X0') + 
           disc_weights[1] * QubitOperator('Y0') )
```

which measures the X & Y expectation values of qubit 0 and 1 and multiplies them with the coefficients named disc_weights[0] & disc_weights[1] respectively. How do I get a matrix representation of this?

**Comment by obriente** [comment]
You can use the 'get_sparse_operator' function and then cast to dense:
`
from openfermion import get_sparse_operator
matrix = get_sparse_operator(psi).todense()
`
