### ISSUE TITLE
no attribute 'final_state_vector' -- this error occurs with several of the tutorials (my first git post, hope it is sensible, could not find in search)

### ISSUE THREAD

**Issue by hfitzhugh** [quantumlib/OpenFermion#667]
Here is an error I receive while running the circuits_1_basis_change notebook tutorial.  Other tutorials produce the same error.
Thank you.

AttributeError                            Traceback (most recent call last)
<ipython-input-15-c95cdb2b3c9b> in <module>
     13 result = simulator.simulate(circuit, qubit_order=qubits,
     14                             initial_state=initial_state)
---> 15 simulated_state = result.final_state_vector
     16 
     17 # Print final fidelity.

AttributeError: 'WaveFunctionTrialResult' object has no attribute 'final_state_vector'

**Comment by vtomole** [comment]
What versions of Python, Cirq and Openfermion are you running?

**Comment by hfitzhugh** [comment]
I performed the developer installation of OpenFermion several hours ago using:

git clone https://github.com/quantumlib/OpenFermion
cd OpenFermion
python -m pip install -e .

Python version is 3.8.5, as chosen by the conda environment I created for this, I presume.

For Cirq, if I have this it is the version that would come upon the above installation.  I did not explicitly add or install cirq.  I did notice that some of the circuit mapping outputs in the tutorials worked ok, if that is an indication.  (The stated error in the initial post is the only error I have encountered.)

Perhaps there is a non-development version that would be better for me? For now, I am going to use OpenFermion in a course project. (I will eventually want to try using OF for proper academic studies of 'single molecule magnet'-type systems)

Thank you very much for your response.
- Henry

**Comment by ncrubin** [comment]
Hi Henry,  could you post the exact code here if you are still having this issue?

**Comment by ncrubin** [comment]
Okay I got to the bottom of this.  The problem is that openfermion is pinned to Cirq.0.8. WaveFunctionTrialResult had an attribute `final_state` which in `TrialSimulationResult` is `final_state_vector`.  A bunch of stuff has moved under us so I am going to bump the version of cirq we are pinning.

**Comment by ncrubin** [comment]
#684 fixes this.
