### ISSUE TITLE
Automatic selection of active orbitals

### ISSUE THREAD

**Issue by PabloAMC** [quantumlib/OpenFermion#707]
Although OpenFermion allows specifying the orbitals from the active space, there is currently no implementation of how to select them automatically. Would this be easy to implement?

**Comment by ncrubin** [comment]
Hi @PabloAMC,  Selecting an active space is one of the most challenging pieces of a post-HF calculation.  While OpenFermion does not support automatic active space selection there are tools in pyscf that do this for you.  For example, AVAS (https://github.com/pyscf/pyscf-doc/blob/master/examples/mcscf/43-avas.py) is one such tool.  Even with AVAS there is problem specific tuning.  I would think of the automated methods as a starting point to be confirmed by your intuition.   There are also easier approaches such as UNO-CAS but require that that UHF solution is different from the RHF solution.
