### ISSUE TITLE
check python 3.8 support

### ISSUE THREAD

**Issue by ncrubin** [quantumlib/OpenFermion#715]
Expand the supported python versions by checking newer pythons and functionality.

**Comment by jitendrs** [comment]
Hi @ncrubin Can you assign this issue to me.

**Comment by ncrubin** [comment]
@jitendrs thanks for taking a look at this!

**Comment by jitendrs** [comment]
@ncrubin Thank you.

**Comment by ncrubin** [comment]
any news on this?  It would be nice to add the 3.8 tag to OpenFermion

**Comment by jitendrs** [comment]
@ncrubin I am still working on it. I will try to list out changes soon for validation.

**Comment by ncrubin** [comment]
We now test against python 3.8 and 3.9 in our CI so this issue can be closed
