### ISSUE TITLE
Latest Cirq release conflicts with OpenFermion requirements

### ISSUE THREAD

**Issue by xabomon** [quantumlib/OpenFermion#718]
Hi all,

I'm experiencing conflicts between latest cirq release (v0.10.0) and the cirq requirements in Openfermion (v0.9).

How long would it take for this to be updated?

**Comment by ncrubin** [comment]
I pushed a new version to pypi 1.0.1 which works with v0.10.0 cirq.   OpenFermion (v0.9) certainly had issues which the 1.0.1 cut works out.
