### ISSUE TITLE
Are there plans to implement double rank factorization or tensor hypercontraction methods?

### ISSUE THREAD

**Issue by PabloAMC** [quantumlib/OpenFermion#723]
Are there plans to include in OpenFermion methods to perform the double rank factorization method of [https://arxiv.org/pdf/2007.14460](https://arxiv.org/pdf/2007.14460) and the tensor hypercontraction method [https://arxiv.org/pdf/2011.03494](https://arxiv.org/pdf/2011.03494), for example once they are published?
Thanks!

**Comment by babbush** [comment]
I am not sure if we will include the double factorization method. It would definitely be in scope though and we'd welcome the contribution. The tensor factorization method is available in QChem and we will likely also add functionality to OpenFermion to use it in the context of fault-tolerant resource estimates, eventually. That's a larger project on a roadmap but I can't say when we would be finished with adding the functionality.

**Comment by PabloAMC** [comment]
The features requested have been included in the merged PR above and are now available (https://github.com/quantumlib/OpenFermion/tree/master/src/openfermion/resource_estimates).
Thanks for including them!
