### ISSUE TITLE
Failed to import Ansatz from Openfermioncirq

### ISSUE THREAD

**Issue by ChrisW918** [quantumlib/OpenFermion#732]
I followed the instruction in github to import types of ansatz from _openfermioncirq.varional_ , but it reports the fault:

ModuleNotFoundError: No module named 'openfermion.ops._givens_rotations'

I tried to check the _ops_ package, and it turns out that _givens_rotations_ has been removed.

How can I fix this? Or is there other ways to import ansatz?

**Comment by obriente** [comment]
Hi Chris,

The file you want can be found in openfermion.linalg now instead of openfermion.ops .

Openfermioncirq has been depreciated, so it's not so surprising that the links are broken. You can find most of what you might be looking for these days in openfermion.circuits .

Cheers,

Tom.

**Comment by ChrisW918** [comment]
> Hi Chris,
> 
> The file you want can be found in openfermion.linalg now instead of openfermion.ops .
> 
> Openfermioncirq has been depreciated, so it's not so surprising that the links are broken. You can find most of what you might be looking for these days in openfermion.circuits .
> 
> Cheers,
> 
> Tom.

Hi Tom,

Cool. I was trying to structure ansatz for calculating optimal ground-state-energy, yet it seems all the tutorials or illustrations online are overdue. 

Do you updated any available source?

**Comment by obriente** [comment]
@tanujkhattar , do the tutorials that you were drafting still work on the current version of openfermion? They haven't been added to master yet but perhaps they're still valuable to Chris.

@ChrisW918 , apologies, the openfermion tutorials for VQEs are bit out of date (mainly because most of the workflow is done using cirq these days). For the actual variational loop, you can have a look at https://quantumai.google/cirq/tutorials/variational_algorithm perhaps, or for a real example I'd recommend the hfvqe example in recirq - https://github.com/quantumlib/ReCirq/tree/master/recirq/hfvqe .

**Comment by ChrisW918** [comment]
Thanks @obriente . I tried to def a cost_function to run iteration, yet the results were not expected. 
Could you help me check the code please?


set up the basics of a molecule
```
geometry=[['H',[.0, .0, .0]],
         ['H', [.0, .0, .74]]]
basis='sto-3g'
multiplicity=1
charge=0
```

initiate molecule's structure
```
molecule=MolecularData(geometry, basis, multiplicity, charge)
molecule=run_pyscf(molecule,
                  run_mp2=True,
                  run_cisd=True,
                  run_ccsd=True,
                  run_fci=True)
```

#create the packed_amplitudes for later inputs
```
n_qubit=molecule.n_qubits
n_electron=molecule.n_electrons

package=uccsd_singlet_get_packed_amplitudes(molecule.ccsd_single_amps, 
                                            molecule.ccsd_double_amps,
                                            n_qubit, 
                                            n_electron)
```

#def the cost_function
```
def cost(package):
    fermionic_hamiltonian=uccsd_singlet_generator(package,
                                                 n_qubit,
                                                 n_electron,
                                                 anti_hermitian=True)
    qubit_hamiltonian=jordan_wigner(fermionic_hamiltonian)
    sparse_hamiltonian=get_sparse_operator(qubit_hamiltonian)
    energy, state=get_ground_state(sparse_hamiltonian)
    return energy
```

#run iteration
```
res=minimize(cost,
            package,
            method='SLSQP',
            options={'xatol': 1e-8, 'disp': True})

```


The function value of my current set up returns

```
Optimization terminated successfully    (Exit mode 0)
            Current function value: -1.619690134165458e-19
            Iterations: 1
            Function evaluations: 3
            Gradient evaluations: 1
```

Seems the function does not pass the optimization automatically at all, and the value is not displayed in Angstrom.

There must be things wrong about my cost_function. Is it because the use of _sparse_hamiltonian_?

**Comment by ChrisW918** [comment]
Sorry, it seems I didn't join Cirq in the function, yet I wonder for which function's output is an available observable for Cirq to exacute?

**Comment by tanujkhattar** [comment]
@obriente yes, the draft still works with the latest openfermion but the VQE tutorial was supposed to come in part-2, which never happened. 

@ChrisW918 To give you a brief example of how to create and optimize an ansatz using Cirq, please see this example: https://colab.research.google.com/drive/1E7kgzBg_uUX58SA5ENHS4A1GVXJh2xtf?usp=sharing

**Comment by ChrisW918** [comment]
@tanujkhattar Thanks. And I noticed that the optimization used in your example is COBYLA, which accepts imaginary parameters, yet when I tried to apply optimizer like 'SLSQP' or 'Nelder-Mead', the program reports the direct cause of the exception is 

`TypeError: can't convert complex to float`

It seems the generated parameters from ansatz is a list of imaginary numbers. Is imaginary parameter necessary here? Or do you have other options to apply SLSQP and Nelder-Mead?

**Comment by tanujkhattar** [comment]
Since all the coefficients of the pauli terms in our `pauli_sum_hamiltonian` are real numbers, `p.estimated_energy()` will always return a complex number with imaginary part == 0.  I've sent a PR in Cirq to ensure that `p.estimated_energy` returns a `float` instead of `complex`. But in the meantime, returning `p.estimated_energy().real` from the cost function should be sufficient to support other optimizers like `SLSQP` or `Nelder-Mead`.

**Comment by ChrisW918** [comment]
@tanujkhattar Thanks for your expanation! I'm going to close this issue.
