### ISSUE TITLE
Possible bug in InteractionRDM.get_qubit_expectations()

### ISSUE THREAD

**Issue by cvjjm** [quantumlib/OpenFermion#733]
I think I may have fond a bug in:

https://github.com/quantumlib/OpenFermion/blob/9b1c22cae2124cf1d4e48d6d123767f8491a0b41/src/openfermion/ops/representations/interaction_rdm.py#L95

Running the very simple example code:
```
op = InteractionRDM(np.diag([1, 1, 1, 1]), np.zeros((4, 4, 4, 4)))
[
    op.get_qubit_expectations(QubitOperator('Z0 Z1')), 
    op.get_qubit_expectations(QubitOperator('Z0')),
    op.get_qubit_expectations(QubitOperator('Z1'))
}
```
returns the result `[-3.0, -1.0, -1.0]`.

In my understanding of the documentation is that `InteractionRDM(np.diag([1, 1, 1, 1]), np.zeros((4, 4, 4, 4)))` should correspond to an RDM of a four (spin) orbital system (fully) occupied by four (uncorrelated) fermions, i.e., in state |1111>. This is consistent with the expectation values of Z0 and Z1 being -1.0 but Z0 Z1 should equally have expectation value -1.0, shouldn't it?

**Comment by cvjjm** [comment]
I fooled myself when cooking up the minimal example (of course my RDM is non-representable and thus the strange return value exceeding the operator norm of the observable is possible). I still think there is a problem but I will have to get back to you with a better example.

**Comment by ncrubin** [comment]
ah..representability...

**Comment by ncrubin** [comment]
@cvjjm do you still think there is a problem?

**Comment by cvjjm** [comment]
Sorry, I forgot to close this. All fine.
