### ISSUE TITLE
Question: How to convert InteractionOperator.one_body_tensor to one_body_integrals (respectively two_body)?

### ISSUE THREAD

**Issue by PabloAMC** [quantumlib/OpenFermion#744]
Hi!
I have `one_body_tensor` and a `two_body_tensor` corresponding to an InteractionOperator from a Hamiltonian. 

**How can they be converted to `MolecularData.one_body_integrals` or `MolecularData.two_body_integrals` format?**

I think the opposite can be done using
```
one_body_coefficients, two_body_coefficients = spinorb_from_spatial(one_body_integrals, two_body_integrals)
one_body_tensor = one_body_coefficients
two_body_tensor = 1/2 * two_body_coefficients
```
according to https://github.com/quantumlib/OpenFermion/blob/40f4dd293d3ac7759e39b0d4c061b391e9663246/src/openfermion/chem/molecular_data.py#L906-L911
Thanks!

**Comment by ncrubin** [comment]
for one body tensor you can take the even or odd indices which will be exactly the one_body_integrals.  The two_body you are correct in scaling by 2.
