### ISSUE TITLE
Possible small error in tutorial example code?

### ISSUE THREAD

**Issue by cb2014** [quantumlib/OpenFermion#745]
In the tutorial code,
https://github.com/quantumlib/OpenFermion/blob/master/docs/tutorials/intro_to_openfermion.ipynb, under the heading "InteractionOperator and InteractionRDM...", there is the following block of code,

`for p in range(n_orbitals):
    for q in range(p + 1, n_orbitals):
        kappa[p, q] = random_angles[index]
        kappa[q, p] = -numpy.conjugate(random_angles[index])
        index += 1

    # Build the unitary rotation matrix.
    difference_matrix = kappa + kappa.transpose()
    rotation_matrix = scipy.linalg.expm(kappa)

    # Apply the unitary.
    molecular_hamiltonian.rotate_basis(rotation_matrix)`

It seems to me that the last two blocks should not be indented, i.e. should be outside the p-loop. The way it is, the bases get rotated n_orbital times, for which I don't see a reason, even though it essentially does no harm. Indeed, when I removed the indents (taking them out of the p-loop), the agreement on ground state energy gets slight better, i.e. "more" iso-spectral. Presumably repeated base rotations accumulated some error, albeit the error is still very small. 
Anyway, I could be mistaken, but I thought I should ask in case no one has raised the issue.

**Comment by ncrubin** [comment]
You are right.  It shouldn't be indented.  The loops are for forming the generator matrix kappa.  Indeed we are rotating with some partial kappa every time which isn't the intended function based on the text.  Thanks for finding the issue.  Feel free to open a PR to change it.  If I don't hear back in a couple of days I'll get around to making the change over the weekend.

**Comment by cb2014** [comment]
Glad to know I am not mistaken. As far as fixing it, I'm not hacker enough to be able to handle it (don't even know what "opening a PR" means) and will leave it to the pros. Thanks!
