### ISSUE TITLE
bogoliubov_transform and optimal_givens_decomposition differ by transpose

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion#760]
The two routines have largely the same functionality but unfortunately differ by a transpose in their input. For example:
```python
import cirq
from openfermion import bogoliubov_transform, optimal_givens_decomposition

n_qubits = 5
qubits = cirq.LineQubit.range(n_qubits)
mat = cirq.testing.random_unitary(n_qubits)

circuit1 = cirq.Circuit(bogoliubov_transform(qubits, mat))
circuit2 = cirq.Circuit(optimal_givens_decomposition(qubits, mat))

cirq.testing.assert_allclose_up_to_global_phase(cirq.unitary(circuit1), cirq.unitary(circuit2), atol=1e-7)
```
raises an AssertionError but if the line
```python
circuit2 = cirq.Circuit(optimal_givens_decomposition(qubits, mat))
```
is changed to
```python
circuit2 = cirq.Circuit(optimal_givens_decomposition(qubits, mat.T))
```
then there is no error.

These routines should actually be merged into one. The difference between the two routines is that `bogoliubov_transform` includes an argument that can be used to optimize the circuit if the initial state is known, but `optimal_givens_decomposition` has a more efficient overall strategy. These routines should be merged into one routine that uses the more efficient strategy, but can also optimize the circuit based on the initial state.

**Comment by ncrubin** [comment]
do you recall if bogoliubov_transform is using the Clements algorithm to construct the circuit?  If not then they should not be merged into one.

**Comment by kevinsung** [comment]
`bogoliubov_transform` does not use the Clements algorithm, which means that using `bogoliubov_transform` without specifying the initial state is obsoleted by `optimal_givens_decomposition`. However, if the initial state is specified then the algorithm used by `bogoliubov_transform` is actually more efficient than the Clements algorithm. That's why I think the functions should be merged. Instead of having two separate functions for performing the same task, one of which partially obsoletes the other, there should be one function for performing the task which uses the best algorithm in all cases. As for which name we should keep, I'm partial to `bogoliubov_transform` because it describes the logical operation being done; this is consistent with the other circuit routines in the library.

**Comment by ncrubin** [comment]
They should not be merged because they are performing different
algorithms.  Researchers should have the option to pick which one they want
to use.  It is not the job of openfermion to make quadratic Hamiltonian
implementation blackbox.  Clements can be used more broadly for shadow
tomography and such.

**Comment by kevinsung** [comment]
That's a valid point. However, in this case the "different algorithms" are based on the same idea (decomposing the unitary into Givens rotations), so it seems to me that one strategy really does completely obsolete the other.

**Comment by ncrubin** [comment]
In optimal_decomposion there isn't a good way to take advantage of particle number.  One algorithm does not obsolete the other.  If you'd like to submit a PR based on your prior observation updating the documentation to say that one of these methods implements U^{dag} then that would be good.  Otherwise I will close this issue.
