### ISSUE TITLE
Inconsistent bits for rotations in DF and THC resource estimates

### ISSUE THREAD

**Issue by wpol-psiq** [quantumlib/OpenFermion#766]
In both the double-factorization and tensor hypercontraction versions of qubitization detailed in the [THC paper](https://arxiv.org/abs/2011.03494), we often need to load angles or coefficients into our computation. These angles need to be represented by some number of bits; in this paper in particular, we have `aleph` and `beth`.

In the [DF](https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/resource_estimates/df/compute_cost_df.py) and [THC](https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/resource_estimates/thc/compute_cost_thc.py) cost estimate scripts in OpenFermion, the cost functions take these values as arguments rather than compute them using equations found in the paper (like `aleph = ceil(2.5 + log(10*lambda/eps))` on pg. 16 just under Eq. 33). I have noticed that the values one gets for these bits when using the equations in the paper and the chosen values for these bits in [some FeMoco test estimates](https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/resource_estimates/df/compute_cost_df_test.py) differ from each other somewhat. It does not seem like such a big difference, but leads (in some cases) to a 5x-10x difference in Toffoli cost for these algorithms. 

Is there a reason for the particular choices of these values in these test scripts for FeMoco, and if so, why does it differ from the expressions in the paper?

**Comment by ncrubin** [comment]
just as the cutoffs for these factorizations can be numerically determined so can the bits of precision.  For the THC paper I believe this is what they did...but I'm not sure.
