### ISSUE TITLE
Obtaining Fock matrix

### ISSUE THREAD

**Issue by snow0369** [quantumlib/OpenFermion#773]
Even though there is the `fock_matrix` attribute in the documentation of `MolecularData`, it doesn't seem to be implemented.
Could you make an update here, please?

**Comment by ncrubin** [comment]
Let me expand, In canonical orbitals the fock matrix is diagonal with entries as the MO-energies.  So you could construct it simply.  In non-canonical orbitals (an arbitrary orthogonal basis) you can construct the fock operator in the usual way.

**Comment by snow0369** [comment]
Sorry for the late reply. I mean the Fock matrix in terms of atomic orbitals, which is discussed [here](http://forum.psicode.org/t/fock-matrix-in-original-basis/1570). Though there is a mention of this attribute in the docstring of `MolecularData`, in this [line](https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/chem/molecular_data.py#L291), I couldn't find its actual implementation.

**Comment by snow0369** [comment]
> Collaborator

I am using both of them, having the same problem. Thank you.

**Comment by snow0369** [comment]
Ahh, I realized that it can be derived from Roothaan's equation since the canonical orbital, overlap, and orbital energies are given.
