### ISSUE TITLE
Not compatible with the latest release of cirq - 1.0.0

### ISSUE THREAD

**Issue by yurivict** [quantumlib/OpenFermion#789]
[Line](https://github.com/quantumlib/OpenFermion/blob/master/requirements.txt#L1).

**Comment by ncrubin** [comment]
Can you elaborate on this a bit more?  I've been working with the 0.15.0 and 1.0 release and everything seems fine.

**Comment by yurivict** [comment]
This was perhaps a version mismatch at some point.
There is no problem now.

Thank you.
