### ISSUE TITLE
OpenFermion-Dirac breaks with the current version of OpenFermion

### ISSUE THREAD

**Issue by yurivict** [quantumlib/OpenFermion#796]
The README says that Dirac is supported, but all examples in OpenFermion-Dirac break: https://github.com/bsenjean/Openfermion-Dirac/issues/6

**Comment by ncrubin** [comment]
I've left a comment on the OpenFermion-DIRAC repository (https://github.com/bsenjean/Openfermion-Dirac/issues/6#issuecomment-1212582066)

eigenspectrum was moved from utils to linalg.sparse_tools.py. This change needs to occur for almost all examples in OF-DIRAC.

**Comment by bsenjean** [comment]
Hi Nicholas,

Sure, I'll do ASAP ;)

Best,
Bruno

Le ven. 12 août 2022 à 01:17, Nicholas Rubin ***@***.***> a
écrit :

**Comment by bsenjean** [comment]
This is fixed ;)

**Comment by yurivict** [comment]
Thanks!
