### ISSUE TITLE
Deprecated usage of `scipy.optimize.optimize import OptimizeResult`

### ISSUE THREAD

**Issue by vprusso** [quantumlib/OpenFermion#797]
In files [hartree_fock_test.py](https://github.com/quantumlib/OpenFermion/blob/7c3581ad75716d1ff6a0043a516d271052a90e35/src/openfermion/hamiltonians/hartree_fock_test.py) and [hartree_fock.py](https://github.com/quantumlib/OpenFermion/blob/7c3581ad75716d1ff6a0043a516d271052a90e35/src/openfermion/hamiltonians/hartree_fock.py) the import pattern of

```python
from scipy.optimize.optimize import OptimizeResult
```

yields the following deprecation warning:

```
DeprecationWarning: Please use `OptimizeResult` from the `scipy.optimize` namespace, the `scipy.optimize.optimize` namespace is deprecated.
```

The fix for this should simply be to alter `from scipy.optimize.optimize import OptimizeResult` to `from scipy.optimize import OptimizeResult` in both the `hartree_fock.py` and `hartee_fock_test.py` files to eliminate this warning.

**Comment by fdmalone** [comment]
Closing following merging of #811.
