### ISSUE TITLE
scipy > 1.9.3 breaks QuarticFermionicSimulationGate decompose method.  

### ISSUE THREAD

**Issue by fdmalone** [quantumlib/OpenFermion#815]
Tracking this here. A bug was introduced into scipy for linalg.sqrtm for complex valued matrices which appears starting v1.10.0 (see [#18250](https://github.com/scipy/scipy/issues/18250)). This causes our tests to fail for QuarticFermionicSimulationGate due to loss of precision. I'll pin the scipy dependency to < 1.10.0 for the moment.

**Comment by yurivict** [comment]
@fdmalone 

Do you know if there is a fix for this?

**Comment by fdmalone** [comment]
It hasn't been fixed in scipy yet, but there does look to be an open PR. If there's no more activity there we may need to implement our own OR relax our test thresholds. The square root function is only used once in openfermion.

**Comment by fdmalone** [comment]
I'll look into it. Worst case we could probably just write a custom square root function.

**Comment by fdmalone** [comment]
Fixed with #864
