### ISSUE TITLE
Why does MajoranaOperator not subclass SymbolicOperator?

### ISSUE THREAD

**Issue by cvjjm** [quantumlib/OpenFermion#827]
It seems odd that MajoranaOperator is not a sub-class of SymbolicOperator. A notable side effect is that contrary to QubitOperator and other SymbolicOperators, MajoranaOperator does not auto-remove terms that are below EQ_TOLERANCE. Not the end of the world but a strange inconsistency...

**Comment by kevinsung** [comment]
SymbolicOperator stores `(index, action)` pairs. For MajoranaOperator, there is no `action`, so it does not quite map onto the SymbolicOperator class.
