### ISSUE TITLE
91 tests fail

### ISSUE THREAD

**Issue by yurivict** [quantumlib/OpenFermion#851]
See the [log](https://people.freebsd.org/~yuri/py-OpenFermion-1.6.0-tests.log).

Version: 1.6.0
Python-3.9
FreeBSD 13.2

**Comment by fdmalone** [comment]
Thanks for raising this. The tests that are failing are due to a bug in scipy #815. What version of scipy are you using? Was openfermion installed via pip?

**Comment by fdmalone** [comment]
From [here](https://www.freshports.org/science/py-OpenFermion/#packages) it looks like the additional upper limit on scipy isn't being pulled in from https://github.com/quantumlib/OpenFermion/blob/master/dev_tools/requirements/deps/runtime.txt.

**Comment by yurivict** [comment]
We have scipy-1.11.1

OpenFermion was installed using the FreeBSD port, not pip.

**Comment by fdmalone** [comment]
How are your build dependencies pulled in? Do you manually edit the [Makefile](https://github.com/FreeBSD/freebsd-ports/commit/333a451d5826e4f8771088d9ad9b9d5124bca0d5#diff-20d3a33cbc8a8d5eb1f148bfb9ccac5df5d56dbade81b806620cd2df40b35416R14)?
Or should these changes be pulled automatically from the openfermion requirements?

![Screenshot 2023-10-30 at 10 42 33 AM](https://github.com/quantumlib/OpenFermion/assets/12097876/8255ab45-e38e-46d5-b08a-aab5482f8690)

**Comment by yurivict** [comment]
Unfortunately, in the context of the ports framework we can't pull arbitrary versions of dependencies, because the dependency packages have fixed versions.

This explains the problem, thank you.

We will wait for the fix in scipy then.

**Comment by fdmalone** [comment]
Ok, thanks for your understanding! I'll keep this open for the moment so we can track it.

**Comment by fdmalone** [comment]
@yurivict this scipy issue is now resolved so I will close this. I will cut a new patch release shortly and (hopefully) these test failures will disappear.
