### ISSUE TITLE
Operation between MajoranaOperator and numbers?

### ISSUE THREAD

**Issue by snow0369** [quantumlib/OpenFermion#862]
Although `MajoranaOperator` is not a subclass of `SymbolicOperator`, as explained in detail [here](https://github.com/quantumlib/OpenFermion/issues/827), I believe that it should work with numbers.
Currently, only the following methods accept a number as an operand: `__mul__`, `__imul__`, `__rmul__`, `__truediv__`, and `__itruediv__`.

I would like to understand if there is a specific rationale behind the absence of implementations for `identity()` and operations like `__add__` with numbers.

Thank you.

**Comment by kevinsung** [comment]
>I would like to understand if there is a specific rationale behind the absence of implementations for identity() and operations like __add__ with numbers.

As far as I remember, I don't think there was a specific rationale. Adding those methods simply wasn't deemed important enough at the time, but I think they would be a welcome addition.

**Comment by snow0369** [comment]
> What do you mean work with numbers exactly? @kevinsung implemented this so might have some more insights on the design decisions.

Sorry for the lack of the detail. I meant work with numbers as taking numbers (such as `int`, `float` and `complex`) as an input to the operations like `__add__` and `__sub__`.

> As far as I remember, I don't think there was a specific rationale. Adding those methods simply wasn't deemed important enough at the time, but I think they would be a welcome addition.

Then, I am happy to be assigned for that.

While I work on it, I think there is a bug in `__isub__`[(here)](https://github.com/quantumlib/OpenFermion/blob/master/src/openfermion/ops/operators/majorana_operator.py#L152):

```
    def __isub__(self, other):
        if not isinstance(other, type(self)):
            return NotImplemented

        for term, coefficient in other.terms.items():
            if term in self.terms:
                self.terms[term] -= coefficient
            else:
                self.terms[term] = coefficient  # <- Here, shouldn't it be -coefficient?

        return self
```

Thank you.

**Comment by snow0369** [comment]
@fdmalone Hi, I want to gently remind you about the [pull request](https://github.com/quantumlib/OpenFermion/pull/868). I fixed a bug in the subtraction between two Majorana operators, and updated operation between Majorana operator and numbers. Thank you for your attention.

**Comment by fdmalone** [comment]
my bad. Thanks for the contribution.
